# Precise Federal Laws Patterns
# Simple, exact regex patterns for each federal law from leyes_reglamentos_federales.csv
# Auto-generated precise patterns for each law

LAWS_REGEX = [
    (r"\bCódigo\s+Civil\s+Federal\b", "CÓDIGO CIVIL FEDERAL", "CODIGO_FEDERAL"),
    (r"\bCódigo\s+de\s+Comercio\b", "CÓDIGO DE COMERCIO", "CODIGO"),
    (r"\bCódigo\s+de\s+Justicia\s+Militar\b", "CÓDIGO DE JUSTICIA MILITAR", "CODIGO"),
    (r"\bCódigo\s+Federal\s+de\s+Procedimientos\s+Civiles\b", "CÓDIGO FEDERAL DE PROCEDIMIENTOS CIVILES", "CODIGO_FEDERAL"),
    (r"\bCódigo\s+Fiscal\s+de\s+la\s+Federación\b", "CÓDIGO FISCAL DE LA FEDERACIÓN", "CODIGO"),
    (r"\bCódigo\s+Militar\s+de\s+Procedimientos\s+Penales\b", "CÓDIGO MILITAR DE PROCEDIMIENTOS PENALES", "CODIGO"),
    (r"\bCódigo\s+Nacional\s+de\s+Procedimientos\s+Civiles\s+y\s+Familiares\b", "CÓDIGO NACIONAL DE PROCEDIMIENTOS CIVILES Y FAMILIARES", "CODIGO"),
    (r"\bCódigo\s+Nacional\s+de\s+Procedimientos\s+Penales\b", "CÓDIGO NACIONAL DE PROCEDIMIENTOS PENALES", "CODIGO"),
    (r"\bCódigo\s+Penal\s+Federal\b", "CÓDIGO PENAL FEDERAL", "CODIGO_FEDERAL"),
    (r"\bImpuesto\s+Sobre\s+Servicios\s+Expresamente\s+Declarados\s+de\s+Interés\s+Público\s+por\s+Ley,\s+en\s+los\s+que\s+Intervengan\s+Empresas\s+Concesionarias\s+de\s+Bienes\s+del\s+Dominio\s+Directo\s+de\s+la\s+Nación\s+\(LEY\s+que\s+establece,\s+reforma\s+y\s+adiciona\s+las\s+disposiciones\s+relativas\s+a\s+diversos\s+impuestos\)\b", "IMPUESTO SOBRE SERVICIOS EXPRESAMENTE DECLARADOS DE INTERÉS PÚBLICO POR LEY, EN LOS QUE INTERVENGAN EMPRESAS CONCESIONARIAS DE BIENES DEL DOMINIO DIRECTO DE LA NACIÓN (LEY QUE ESTABLECE, REFORMA Y ADICIONA LAS DISPOSICIONES RELATIVAS A DIVERSOS IMPUESTOS)", "LEY"),
    (r"\bLey\s+Aduanera\b", "LEY ADUANERA", "LEY"),
    (r"\bLey\s+Agraria\b", "LEY AGRARIA", "LEY"),
    (r"\bLey\s+de\s+Aeropuertos\b", "LEY DE AEROPUERTOS", "LEY"),
    (r"\bLey\s+de\s+Aguas\s+Nacionales\b", "LEY DE AGUAS NACIONALES", "LEY"),
    (r"\bLey\s+de\s+Ahorro\s+y\s+Crédito\s+Popular\b", "LEY DE AHORRO Y CRÉDITO POPULAR", "LEY"),
    (r"\bLey\s+de\s+Amnistía\b", "LEY DE AMNISTÍA", "LEY"),
    (r"\bLey\s+de\s+Amparo,\s+Reglamentaria\s+de\s+los\s+Artículos\s+103\s+y\s+107\s+de\s+la\s+Constitución\s+Política\s+de\s+los\s+Estados\s+Unidos\s+Mexicanos\b", "LEY DE AMPARO, REGLAMENTARIA DE LOS ARTÍCULOS 103 Y 107 DE LA CONSTITUCIÓN POLÍTICA DE LOS ESTADOS UNIDOS MEXICANOS", "CONSTITUCION"),
    (r"\bLey\s+de\s+Ascensos\s+de\s+la\s+Armada\s+de\s+México\b", "LEY DE ASCENSOS DE LA ARMADA DE MÉXICO", "LEY"),
    (r"\bLey\s+de\s+Ascensos\s+y\s+Recompensas\s+del\s+Ejército\s+y\s+Fuerza\s+Aérea\s+Mexicanos\b", "LEY DE ASCENSOS Y RECOMPENSAS DEL EJÉRCITO Y FUERZA AÉREA MEXICANOS", "LEY"),
    (r"\bLey\s+de\s+Asistencia\s+Social\b", "LEY DE ASISTENCIA SOCIAL", "LEY"),
    (r"\bLey\s+de\s+Asociaciones\s+Público\s+Privadas\b", "LEY DE ASOCIACIONES PÚBLICO PRIVADAS", "LEY"),
    (r"\bLey\s+de\s+Asociaciones\s+Religiosas\s+y\s+Culto\s+Público\b", "LEY DE ASOCIACIONES RELIGIOSAS Y CULTO PÚBLICO", "LEY"),
    (r"\bLey\s+de\s+Aviación\s+Civil\b", "LEY DE AVIACIÓN CIVIL", "LEY"),
    (r"\bLey\s+de\s+Ayuda\s+Alimentaria\s+para\s+los\s+Trabajadores\b", "LEY DE AYUDA ALIMENTARIA PARA LOS TRABAJADORES", "LEY"),
    (r"\bLey\s+de\s+Biocombustibles\b", "LEY DE BIOCOMBUSTIBLES", "LEY"),
    (r"\bLey\s+de\s+Bioseguridad\s+de\s+Organismos\s+Genéticamente\s+Modificados\b", "LEY DE BIOSEGURIDAD DE ORGANISMOS GENÉTICAMENTE MODIFICADOS", "LEY"),
    (r"\bLey\s+de\s+Cámaras\s+Empresariales\s+y\s+sus\s+Confederaciones\b", "LEY DE CÁMARAS EMPRESARIALES Y SUS CONFEDERACIONES", "LEY"),
    (r"\bLey\s+de\s+Caminos,\s+Puentes\s+y\s+Autotransporte\s+Federal\b", "LEY DE CAMINOS, PUENTES Y AUTOTRANSPORTE FEDERAL", "LEY"),
    (r"\bLey\s+de\s+Capitalización\s+del\s+PROCAMPO\b", "LEY DE CAPITALIZACIÓN DEL PROCAMPO", "LEY"),
    (r"\bLey\s+de\s+Carrera\s+Judicial\s+del\s+Poder\s+Judicial\s+de\s+la\s+Federación\b", "LEY DE CARRERA JUDICIAL DEL PODER JUDICIAL DE LA FEDERACIÓN", "LEY"),
    (r"\bLey\s+de\s+Comercio\s+Exterior\b", "LEY DE COMERCIO EXTERIOR", "LEY"),
    (r"\bLey\s+de\s+Concursos\s+Mercantiles\b", "LEY DE CONCURSOS MERCANTILES", "LEY"),
    (r"\bLey\s+de\s+Contribución\s+de\s+Mejoras\s+por\s+Obras\s+Públicas\s+Federales\s+de\s+Infraestructura\s+Hidráulica\b", "LEY DE CONTRIBUCIÓN DE MEJORAS POR OBRAS PÚBLICAS FEDERALES DE INFRAESTRUCTURA HIDRÁULICA", "LEY"),
    (r"\bLey\s+de\s+Cooperación\s+Internacional\s+para\s+el\s+Desarrollo\b", "LEY DE COOPERACIÓN INTERNACIONAL PARA EL DESARROLLO", "LEY"),
    (r"\bLey\s+de\s+Coordinación\s+Fiscal\b", "LEY DE COORDINACIÓN FISCAL", "LEY"),
    (r"\bLey\s+de\s+Desarrollo\s+Rural\s+Sustentable\b", "LEY DE DESARROLLO RURAL SUSTENTABLE", "LEY"),
    (r"\bLey\s+de\s+Desarrollo\s+Sustentable\s+de\s+la\s+Caña\s+de\s+Azúcar\b", "LEY DE DESARROLLO SUSTENTABLE DE LA CAÑA DE AZÚCAR", "LEY"),
    (r"\bLey\s+de\s+Disciplina\s+del\s+Ejército\s+y\s+Fuerza\s+Aérea\s+Mexicanos\b", "LEY DE DISCIPLINA DEL EJÉRCITO Y FUERZA AÉREA MEXICANOS", "LEY"),
    (r"\bLey\s+de\s+Disciplina\s+Financiera\s+de\s+las\s+Entidades\s+Federativas\s+y\s+los\s+Municipios\b", "LEY DE DISCIPLINA FINANCIERA DE LAS ENTIDADES FEDERATIVAS Y LOS MUNICIPIOS", "LEY"),
    (r"\bLey\s+de\s+Disciplina\s+para\s+el\s+Personal\s+de\s+la\s+Armada\s+de\s+México\b", "LEY DE DISCIPLINA PARA EL PERSONAL DE LA ARMADA DE MÉXICO", "LEY"),
    (r"\bLey\s+de\s+Educación\s+Militar\s+del\s+Ejército\s+y\s+Fuerza\s+Aérea\s+Mexicanos\b", "LEY DE EDUCACIÓN MILITAR DEL EJÉRCITO Y FUERZA AÉREA MEXICANOS", "LEY"),
    (r"\bLey\s+de\s+Educación\s+Naval\b", "LEY DE EDUCACIÓN NAVAL", "LEY"),
    (r"\bLey\s+de\s+Energía\s+para\s+el\s+Campo\b", "LEY DE ENERGÍA PARA EL CAMPO", "LEY"),
    (r"\bLey\s+de\s+Expropiación\b", "LEY DE EXPROPIACIÓN", "LEY"),
    (r"\bLey\s+de\s+Extradición\s+Internacional\b", "LEY DE EXTRADICIÓN INTERNACIONAL", "LEY"),
    (r"\bLey\s+de\s+Firma\s+Electrónica\s+Avanzada\b", "LEY DE FIRMA ELECTRÓNICA AVANZADA", "LEY"),
    (r"\bLey\s+de\s+Fiscalización\s+y\s+Rendición\s+de\s+Cuentas\s+de\s+la\s+Federación\b", "LEY DE FISCALIZACIÓN Y RENDICIÓN DE CUENTAS DE LA FEDERACIÓN", "LEY"),
    (r"\bLey\s+de\s+Fomento\s+a\s+la\s+Confianza\s+Ciudadana\b", "LEY DE FOMENTO A LA CONFIANZA CIUDADANA", "LEY"),
    (r"\bLey\s+de\s+Fomento\s+a\s+la\s+Industria\s+Vitivinícola\b", "LEY DE FOMENTO A LA INDUSTRIA VITIVINÍCOLA", "LEY"),
    (r"\bLey\s+de\s+Fomento\s+para\s+la\s+Lectura\s+y\s+el\s+Libro\b", "LEY DE FOMENTO PARA LA LECTURA Y EL LIBRO", "LEY"),
    (r"\bLey\s+de\s+Fondos\s+de\s+Aseguramiento\s+Agropecuario\s+y\s+Rural\b", "LEY DE FONDOS DE ASEGURAMIENTO AGROPECUARIO Y RURAL", "LEY"),
    (r"\bLey\s+de\s+Fondos\s+de\s+Inversión\b", "LEY DE FONDOS DE INVERSIÓN", "LEY"),
    (r"\bLey\s+de\s+Geotermia\b", "LEY DE GEOTERMIA", "LEY"),
    (r"\bLey\s+de\s+Infraestructura\s+de\s+la\s+Calidad\b", "LEY DE INFRAESTRUCTURA DE LA CALIDAD", "LEY"),
    (r"\bLey\s+de\s+Ingresos\s+de\s+la\s+Federación\s+para\s+el\s+Ejercicio\s+Fiscal\s+de\s+2025\b", "LEY DE INGRESOS DE LA FEDERACIÓN PARA EL EJERCICIO FISCAL DE 2025", "LEY"),
    (r"\bLey\s+de\s+Ingresos\s+sobre\s+Hidrocarburos\b", "LEY DE INGRESOS SOBRE HIDROCARBUROS", "LEY"),
    (r"\bLey\s+de\s+Instituciones\s+de\s+Crédito\b", "LEY DE INSTITUCIONES DE CRÉDITO", "LEY"),
    (r"\bLey\s+de\s+Instituciones\s+de\s+Seguros\s+y\s+de\s+Fianzas\b", "LEY DE INSTITUCIONES DE SEGUROS Y DE FIANZAS", "LEY"),
    (r"\bLey\s+de\s+Inversión\s+Extranjera\b", "LEY DE INVERSIÓN EXTRANJERA", "LEY"),
    (r"\bLey\s+de\s+la\s+Agencia\s+Nacional\s+de\s+Seguridad\s+Industrial\s+y\s+de\s+Protección\s+al\s+Medio\s+Ambiente\s+del\s+Sector\s+Hidrocarburos\b", "LEY DE LA AGENCIA NACIONAL DE SEGURIDAD INDUSTRIAL Y DE PROTECCIÓN AL MEDIO AMBIENTE DEL SECTOR HIDROCARBUROS", "LEY"),
    (r"\bLey\s+de\s+la\s+Casa\s+de\s+Moneda\s+de\s+México\b", "LEY DE LA CASA DE MONEDA DE MÉXICO", "LEY"),
    (r"\bLey\s+de\s+la\s+Comisión\s+Federal\s+de\s+Electricidad\b", "LEY DE LA COMISIÓN FEDERAL DE ELECTRICIDAD", "LEY"),
    (r"\bLey\s+de\s+la\s+Comisión\s+Nacional\s+Bancaria\s+y\s+de\s+Valores\b", "LEY DE LA COMISIÓN NACIONAL BANCARIA Y DE VALORES", "LEY"),
    (r"\bLey\s+de\s+la\s+Comisión\s+Nacional\s+de\s+Energía\b", "LEY DE LA COMISIÓN NACIONAL DE ENERGÍA", "LEY"),
    (r"\bLey\s+de\s+la\s+Comisión\s+Nacional\s+de\s+los\s+Derechos\s+Humanos\b", "LEY DE LA COMISIÓN NACIONAL DE LOS DERECHOS HUMANOS", "LEY"),
    (r"\bLey\s+de\s+la\s+Economía\s+Social\s+y\s+Solidaria\b", "LEY DE LA ECONOMÍA SOCIAL Y SOLIDARIA", "LEY"),
    (r"\bLey\s+de\s+la\s+Empresa\s+Pública\s+del\s+Estado,\s+Comisión\s+Federal\s+de\s+Electricidad\b", "LEY DE LA EMPRESA PÚBLICA DEL ESTADO, COMISIÓN FEDERAL DE ELECTRICIDAD", "LEY"),
    (r"\bLey\s+de\s+la\s+Empresa\s+Pública\s+del\s+Estado,\s+Petróleos\s+Mexicanos\b", "LEY DE LA EMPRESA PÚBLICA DEL ESTADO, PETRÓLEOS MEXICANOS", "LEY"),
    (r"\bLey\s+de\s+la\s+Fiscalía\s+General\s+de\s+la\s+República\b", "LEY DE LA FISCALÍA GENERAL DE LA REPÚBLICA", "LEY"),
    (r"\bLey\s+de\s+la\s+Guardia\s+Nacional\b", "LEY DE LA GUARDIA NACIONAL", "LEY"),
    (r"\bLey\s+de\s+la\s+Policía\s+Federal\b", "LEY DE LA POLICÍA FEDERAL", "LEY"),
    (r"\bLey\s+de\s+los\s+Derechos\s+de\s+las\s+Personas\s+Adultas\s+Mayores\b", "LEY DE LOS DERECHOS DE LAS PERSONAS ADULTAS MAYORES", "LEY"),
    (r"\bLey\s+de\s+los\s+Husos\s+Horarios\s+en\s+los\s+Estados\s+Unidos\s+Mexicanos\b", "LEY DE LOS HUSOS HORARIOS EN LOS ESTADOS UNIDOS MEXICANOS", "LEY"),
    (r"\bLey\s+de\s+los\s+Impuestos\s+Generales\s+de\s+Importación\s+y\s+de\s+Exportación\b", "LEY DE LOS IMPUESTOS GENERALES DE IMPORTACIÓN Y DE EXPORTACIÓN", "LEY"),
    (r"\bLey\s+de\s+los\s+Institutos\s+Nacionales\s+de\s+Salud\b", "LEY DE LOS INSTITUTOS NACIONALES DE SALUD", "LEY"),
    (r"\bLey\s+de\s+los\s+Sistemas\s+de\s+Ahorro\s+para\s+el\s+Retiro\b", "LEY DE LOS SISTEMAS DE AHORRO PARA EL RETIRO", "LEY"),
    (r"\bLey\s+de\s+Migración\b", "LEY DE MIGRACIÓN", "LEY"),
    (r"\bLey\s+de\s+Minería\b", "LEY DE MINERÍA", "LEY"),
    (r"\bLey\s+de\s+Nacionalidad\b", "LEY DE NACIONALIDAD", "LEY"),
    (r"\bLey\s+de\s+Navegación\s+y\s+Comercio\s+Marítimos\b", "LEY DE NAVEGACIÓN Y COMERCIO MARÍTIMOS", "LEY"),
    (r"\bLey\s+de\s+Obras\s+Públicas\s+y\s+Servicios\s+Relacionados\s+con\s+las\s+Mismas\b", "LEY DE OBRAS PÚBLICAS Y SERVICIOS RELACIONADOS CON LAS MISMAS", "LEY"),
    (r"\bLey\s+de\s+Organizaciones\s+Ganaderas\b", "LEY DE ORGANIZACIONES GANADERAS", "LEY"),
    (r"\bLey\s+de\s+Planeación\b", "LEY DE PLANEACIÓN", "LEY"),
    (r"\bLey\s+de\s+Planeación\s+y\s+Transición\s+Energética\b", "LEY DE PLANEACIÓN Y TRANSICIÓN ENERGÉTICA", "LEY"),
    (r"\bLey\s+de\s+Premios,\s+Estímulos\s+y\s+Recompensas\s+Civiles\b", "LEY DE PREMIOS, ESTÍMULOS Y RECOMPENSAS CIVILES", "LEY"),
    (r"\bLey\s+de\s+Productos\s+Orgánicos\b", "LEY DE PRODUCTOS ORGÁNICOS", "LEY"),
    (r"\bLey\s+de\s+Protección\s+al\s+Ahorro\s+Bancario\b", "LEY DE PROTECCIÓN AL AHORRO BANCARIO", "LEY"),
    (r"\bLey\s+de\s+Protección\s+al\s+Comercio\s+y\s+la\s+Inversión\s+de\s+Normas\s+Extranjeras\s+que\s+Contravengan\s+el\s+Derecho\s+Internacional\b", "LEY DE PROTECCIÓN AL COMERCIO Y LA INVERSIÓN DE NORMAS EXTRANJERAS QUE CONTRAVENGAN EL DERECHO INTERNACIONAL", "LEY"),
    (r"\bLey\s+de\s+Protección\s+del\s+Espacio\s+Aéreo\s+Mexicano\b", "LEY DE PROTECCIÓN DEL ESPACIO AÉREO MEXICANO", "LEY"),
    (r"\bLey\s+de\s+Protección\s+y\s+Defensa\s+al\s+Usuario\s+de\s+Servicios\s+Financieros\b", "LEY DE PROTECCIÓN Y DEFENSA AL USUARIO DE SERVICIOS FINANCIEROS", "LEY"),
    (r"\bLey\s+de\s+Puertos\b", "LEY DE PUERTOS", "LEY"),
    (r"\bLey\s+de\s+Recompensas\s+de\s+la\s+Armada\s+de\s+México\b", "LEY DE RECOMPENSAS DE LA ARMADA DE MÉXICO", "LEY"),
    (r"\bLey\s+de\s+Responsabilidad\s+Civil\s+por\s+Daños\s+Nucleares\b", "LEY DE RESPONSABILIDAD CIVIL POR DAÑOS NUCLEARES", "LEY"),
    (r"\bLey\s+de\s+Seguridad\s+Interior\b", "LEY DE SEGURIDAD INTERIOR", "LEY"),
    (r"\bLey\s+de\s+Seguridad\s+Nacional\b", "LEY DE SEGURIDAD NACIONAL", "LEY"),
    (r"\bLey\s+de\s+Sistemas\s+de\s+Pagos\b", "LEY DE SISTEMAS DE PAGOS", "LEY"),
    (r"\bLey\s+de\s+Sociedades\s+de\s+Responsabilidad\s+Limitada\s+de\s+Interés\s+Público\b", "LEY DE SOCIEDADES DE RESPONSABILIDAD LIMITADA DE INTERÉS PÚBLICO", "LEY"),
    (r"\bLey\s+de\s+Sociedades\s+de\s+Solidaridad\s+Social\b", "LEY DE SOCIEDADES DE SOLIDARIDAD SOCIAL", "LEY"),
    (r"\bLey\s+de\s+Tesorería\s+de\s+la\s+Federación\b", "LEY DE TESORERÍA DE LA FEDERACIÓN", "LEY"),
    (r"\bLey\s+de\s+Transparencia\s+y\s+de\s+Fomento\s+a\s+la\s+Competencia\s+en\s+el\s+Crédito\s+Garantizado\b", "LEY DE TRANSPARENCIA Y DE FOMENTO A LA COMPETENCIA EN EL CRÉDITO GARANTIZADO", "LEY"),
    (r"\bLey\s+de\s+Uniones\s+de\s+Crédito\b", "LEY DE UNIONES DE CRÉDITO", "LEY"),
    (r"\bLey\s+de\s+Vertimientos\s+en\s+las\s+Zonas\s+Marinas\s+Mexicanas\b", "LEY DE VERTIMIENTOS EN LAS ZONAS MARINAS MEXICANAS", "LEY"),
    (r"\bLey\s+de\s+Vías\s+Generales\s+de\s+Comunicación\b", "LEY DE VÍAS GENERALES DE COMUNICACIÓN", "LEY"),
    (r"\bLey\s+de\s+Vivienda\b", "LEY DE VIVIENDA", "LEY"),
    (r"\bLey\s+del\s+Banco\s+de\s+México\b", "LEY DEL BANCO DE MÉXICO", "LEY"),
    (r"\bLey\s+del\s+Diario\s+Oficial\s+de\s+la\s+Federación\s+y\s+Gacetas\s+Gubernamentales\b", "LEY DEL DIARIO OFICIAL DE LA FEDERACIÓN Y GACETAS GUBERNAMENTALES", "LEY"),
    (r"\bLey\s+del\s+Fondo\s+Mexicano\s+del\s+Petróleo\s+para\s+la\s+Estabilización\s+y\s+el\s+Desarrollo\b", "LEY DEL FONDO MEXICANO DEL PETRÓLEO PARA LA ESTABILIZACIÓN Y EL DESARROLLO", "LEY"),
    (r"\bLey\s+del\s+Impuesto\s+al\s+Valor\s+Agregado\b", "LEY DEL IMPUESTO AL VALOR AGREGADO", "LEY"),
    (r"\bLey\s+del\s+Impuesto\s+Especial\s+sobre\s+Producción\s+y\s+Servicios\b", "LEY DEL IMPUESTO ESPECIAL SOBRE PRODUCCIÓN Y SERVICIOS", "LEY"),
    (r"\bLey\s+del\s+Impuesto\s+sobre\s+la\s+Renta\b", "LEY DEL IMPUESTO SOBRE LA RENTA", "LEY"),
    (r"\bLey\s+del\s+Instituto\s+de\s+Seguridad\s+Social\s+para\s+las\s+Fuerzas\s+Armadas\s+Mexicanas\b", "LEY DEL INSTITUTO DE SEGURIDAD SOCIAL PARA LAS FUERZAS ARMADAS MEXICANAS", "LEY"),
    (r"\bLey\s+del\s+Instituto\s+de\s+Seguridad\s+y\s+Servicios\s+Sociales\s+de\s+los\s+Trabajadores\s+del\s+Estado\b", "LEY DEL INSTITUTO DE SEGURIDAD Y SERVICIOS SOCIALES DE LOS TRABAJADORES DEL ESTADO", "LEY"),
    (r"\bLey\s+del\s+Instituto\s+del\s+Fondo\s+Nacional\s+de\s+la\s+Vivienda\s+para\s+los\s+Trabajadores\b", "LEY DEL INSTITUTO DEL FONDO NACIONAL DE LA VIVIENDA PARA LOS TRABAJADORES", "LEY"),
    (r"\bLey\s+del\s+Instituto\s+del\s+Fondo\s+Nacional\s+para\s+el\s+Consumo\s+de\s+los\s+Trabajadores\b", "LEY DEL INSTITUTO DEL FONDO NACIONAL PARA EL CONSUMO DE LOS TRABAJADORES", "LEY"),
    (r"\bLey\s+del\s+Instituto\s+Mexicano\s+de\s+la\s+Juventud\b", "LEY DEL INSTITUTO MEXICANO DE LA JUVENTUD", "LEY"),
    (r"\bLey\s+del\s+Instituto\s+Nacional\s+de\s+las\s+Mujeres\b", "LEY DEL INSTITUTO NACIONAL DE LAS MUJERES", "LEY"),
    (r"\bLey\s+del\s+Instituto\s+Nacional\s+de\s+los\s+Pueblos\s+Indígenas\b", "LEY DEL INSTITUTO NACIONAL DE LOS PUEBLOS INDÍGENAS", "LEY"),
    (r"\bLey\s+del\s+Mercado\s+de\s+Valores\b", "LEY DEL MERCADO DE VALORES", "LEY"),
    (r"\bLey\s+del\s+Registro\s+Público\s+Vehicular\b", "LEY DEL REGISTRO PÚBLICO VEHICULAR", "LEY"),
    (r"\bLey\s+del\s+Sector\s+Eléctrico\b", "LEY DEL SECTOR ELÉCTRICO", "LEY"),
    (r"\bLey\s+del\s+Seguro\s+Social\b", "LEY DEL SEGURO SOCIAL", "LEY"),
    (r"\bLey\s+del\s+Servicio\s+de\s+Administración\s+Tributaria\b", "LEY DEL SERVICIO DE ADMINISTRACIÓN TRIBUTARIA", "LEY"),
    (r"\bLey\s+del\s+Servicio\s+Exterior\s+Mexicano\b", "LEY DEL SERVICIO EXTERIOR MEXICANO", "LEY"),
    (r"\bLey\s+del\s+Servicio\s+Militar\b", "LEY DEL SERVICIO MILITAR", "LEY"),
    (r"\bLey\s+del\s+Servicio\s+Postal\s+Mexicano\b", "LEY DEL SERVICIO POSTAL MEXICANO", "LEY"),
    (r"\bLey\s+del\s+Servicio\s+Profesional\s+de\s+Carrera\s+en\s+la\s+Administración\s+Pública\s+Federal\b", "LEY DEL SERVICIO PROFESIONAL DE CARRERA EN LA ADMINISTRACIÓN PÚBLICA FEDERAL", "LEY"),
    (r"\bLey\s+del\s+Sistema\s+Nacional\s+de\s+Información\s+Estadística\s+y\s+Geográfica\b", "LEY DEL SISTEMA NACIONAL DE INFORMACIÓN ESTADÍSTICA Y GEOGRÁFICA", "LEY"),
    (r"\bLey\s+del\s+Sistema\s+Público\s+de\s+Radiodifusión\s+del\s+Estado\s+Mexicano\b", "LEY DEL SISTEMA PÚBLICO DE RADIODIFUSIÓN DEL ESTADO MEXICANO", "LEY"),
    (r"\bLey\s+Federal\s+contra\s+la\s+Delincuencia\s+Organizada\b", "LEY FEDERAL CONTRA LA DELINCUENCIA ORGANIZADA", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+de\s+Armas\s+de\s+Fuego\s+y\s+Explosivos\b", "LEY FEDERAL DE ARMAS DE FUEGO Y EXPLOSIVOS", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+de\s+Austeridad\s+Republicana\b", "LEY FEDERAL DE AUSTERIDAD REPUBLICANA", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+de\s+Cinematografía\b", "LEY FEDERAL DE CINEMATOGRAFÍA", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+de\s+Competencia\s+Económica\b", "LEY FEDERAL DE COMPETENCIA ECONÓMICA", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+de\s+Consulta\s+Popular\b", "LEY FEDERAL DE CONSULTA POPULAR", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+de\s+Correduría\s+Pública\b", "LEY FEDERAL DE CORREDURÍA PÚBLICA", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+de\s+Declaración\s+Especial\s+de\s+Ausencia\s+para\s+Personas\s+Desaparecidas\.\b", "LEY FEDERAL DE DECLARACIÓN ESPECIAL DE AUSENCIA PARA PERSONAS DESAPARECIDAS.", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+de\s+Defensoría\s+Pública\b", "LEY FEDERAL DE DEFENSORÍA PÚBLICA", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+de\s+Derechos\b", "LEY FEDERAL DE DERECHOS", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+de\s+Deuda\s+Pública\b", "LEY FEDERAL DE DEUDA PÚBLICA", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+de\s+Fomento\s+a\s+las\s+Actividades\s+Realizadas\s+por\s+Organizaciones\s+de\s+la\s+Sociedad\s+Civil\b", "LEY FEDERAL DE FOMENTO A LAS ACTIVIDADES REALIZADAS POR ORGANIZACIONES DE LA SOCIEDAD CIVIL", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+de\s+Juegos\s+y\s+Sorteos\b", "LEY FEDERAL DE JUEGOS Y SORTEOS", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+de\s+las\s+Entidades\s+Paraestatales\b", "LEY FEDERAL DE LAS ENTIDADES PARAESTATALES", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+de\s+los\s+Derechos\s+del\s+Contribuyente\b", "LEY FEDERAL DE LOS DERECHOS DEL CONTRIBUYENTE", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+de\s+los\s+Trabajadores\s+al\s+Servicio\s+del\s+Estado,\s+Reglamentaria\s+del\s+Apartado\s+B\)\s+del\s+Artículo\s+123\s+Constitucional\b", "LEY FEDERAL DE LOS TRABAJADORES AL SERVICIO DEL ESTADO, REGLAMENTARIA DEL APARTADO B) DEL ARTÍCULO 123 CONSTITUCIONAL", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+de\s+Presupuesto\s+y\s+Responsabilidad\s+Hacendaria\b", "LEY FEDERAL DE PRESUPUESTO Y RESPONSABILIDAD HACENDARIA", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+de\s+Procedimiento\s+Administrativo\b", "LEY FEDERAL DE PROCEDIMIENTO ADMINISTRATIVO", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+de\s+Procedimiento\s+Contencioso\s+Administrativo\b", "LEY FEDERAL DE PROCEDIMIENTO CONTENCIOSO ADMINISTRATIVO", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+de\s+Producción,\s+Certificación\s+y\s+Comercio\s+de\s+Semillas\b", "LEY FEDERAL DE PRODUCCIÓN, CERTIFICACIÓN Y COMERCIO DE SEMILLAS", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+de\s+Protección\s+a\s+la\s+Propiedad\s+Industrial\b", "LEY FEDERAL DE PROTECCIÓN A LA PROPIEDAD INDUSTRIAL", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+de\s+Protección\s+al\s+Consumidor\b", "LEY FEDERAL DE PROTECCIÓN AL CONSUMIDOR", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+de\s+Protección\s+de\s+Datos\s+Personales\s+en\s+Posesión\s+de\s+los\s+Particulares\b", "LEY FEDERAL DE PROTECCIÓN DE DATOS PERSONALES EN POSESIÓN DE LOS PARTICULARES", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+de\s+Protección\s+del\s+Patrimonio\s+Cultural\s+de\s+los\s+Pueblos\s+y\s+Comunidades\s+Indígenas\s+y\s+Afromexicanas\b", "LEY FEDERAL DE PROTECCIÓN DEL PATRIMONIO CULTURAL DE LOS PUEBLOS Y COMUNIDADES INDÍGENAS Y AFROMEXICANAS", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+de\s+Remuneraciones\s+de\s+los\s+Servidores\s+Públicos\b", "LEY FEDERAL DE REMUNERACIONES DE LOS SERVIDORES PÚBLICOS", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+de\s+Responsabilidad\s+Ambiental\b", "LEY FEDERAL DE RESPONSABILIDAD AMBIENTAL", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+de\s+Responsabilidad\s+Patrimonial\s+del\s+Estado\b", "LEY FEDERAL DE RESPONSABILIDAD PATRIMONIAL DEL ESTADO", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+de\s+Responsabilidades\s+de\s+los\s+Servidores\s+Públicos\b", "LEY FEDERAL DE RESPONSABILIDADES DE LOS SERVIDORES PÚBLICOS", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+de\s+Revocación\s+de\s+Mandato\b", "LEY FEDERAL DE REVOCACIÓN DE MANDATO", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+de\s+Sanidad\s+Animal\b", "LEY FEDERAL DE SANIDAD ANIMAL", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+de\s+Sanidad\s+Vegetal\b", "LEY FEDERAL DE SANIDAD VEGETAL", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+de\s+Seguridad\s+Privada\b", "LEY FEDERAL DE SEGURIDAD PRIVADA", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+de\s+Telecomunicaciones\s+y\s+Radiodifusión\.\b", "LEY FEDERAL DE TELECOMUNICACIONES Y RADIODIFUSIÓN.", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+de\s+Variedades\s+Vegetales\b", "LEY FEDERAL DE VARIEDADES VEGETALES", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+de\s+Zonas\s+Económicas\s+Especiales\b", "LEY FEDERAL DE ZONAS ECONÓMICAS ESPECIALES", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+del\s+Derecho\s+de\s+Autor\b", "LEY FEDERAL DEL DERECHO DE AUTOR", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+del\s+Impuesto\s+sobre\s+Automóviles\s+Nuevos\b", "LEY FEDERAL DEL IMPUESTO SOBRE AUTOMÓVILES NUEVOS", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+del\s+Mar\b", "LEY FEDERAL DEL MAR", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+del\s+Trabajo\b", "LEY FEDERAL DEL TRABAJO", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+para\s+el\s+Control\s+de\s+Precursores\s+Químicos,\s+Productos\s+Químicos\s+Esenciales\s+y\s+Máquinas\s+para\s+Elaborar\s+Cápsulas,\s+Tabletas\s+y/o\s+Comprimidos\b", "LEY FEDERAL PARA EL CONTROL DE PRECURSORES QUÍMICOS, PRODUCTOS QUÍMICOS ESENCIALES Y MÁQUINAS PARA ELABORAR CÁPSULAS, TABLETAS Y/O COMPRIMIDOS", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+para\s+el\s+Control\s+de\s+Sustancias\s+Químicas\s+Susceptibles\s+de\s+Desvío\s+para\s+la\s+Fabricación\s+de\s+Armas\s+Químicas\b", "LEY FEDERAL PARA EL CONTROL DE SUSTANCIAS QUÍMICAS SUSCEPTIBLES DE DESVÍO PARA LA FABRICACIÓN DE ARMAS QUÍMICAS", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+para\s+el\s+Fomento\s+de\s+la\s+Microindustria\s+y\s+la\s+Actividad\s+Artesanal\b", "LEY FEDERAL PARA EL FOMENTO DE LA MICROINDUSTRIA Y LA ACTIVIDAD ARTESANAL", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+para\s+el\s+Fomento\s+y\s+Protección\s+del\s+Maíz\s+Nativo\b", "LEY FEDERAL PARA EL FOMENTO Y PROTECCIÓN DEL MAÍZ NATIVO", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+para\s+la\s+Administración\s+y\s+Enajenación\s+de\s+Bienes\s+del\s+Sector\s+Público\b", "LEY FEDERAL PARA LA ADMINISTRACIÓN Y ENAJENACIÓN DE BIENES DEL SECTOR PÚBLICO", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+para\s+la\s+Prevención\s+e\s+Identificación\s+de\s+Operaciones\s+con\s+Recursos\s+de\s+Procedencia\s+Ilícita\b", "LEY FEDERAL PARA LA PREVENCIÓN E IDENTIFICACIÓN DE OPERACIONES CON RECURSOS DE PROCEDENCIA ILÍCITA", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+para\s+la\s+Protección\s+a\s+Personas\s+que\s+Intervienen\s+en\s+el\s+Procedimiento\s+Penal\b", "LEY FEDERAL PARA LA PROTECCIÓN A PERSONAS QUE INTERVIENEN EN EL PROCEDIMIENTO PENAL", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+para\s+Prevenir\s+y\s+Eliminar\s+la\s+Discriminación\b", "LEY FEDERAL PARA PREVENIR Y ELIMINAR LA DISCRIMINACIÓN", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+para\s+Prevenir\s+y\s+Sancionar\s+los\s+delitos\s+cometidos\s+en\s+materia\s+de\s+Hidrocarburos\b", "LEY FEDERAL PARA PREVENIR Y SANCIONAR LOS DELITOS COMETIDOS EN MATERIA DE HIDROCARBUROS", "LEY_FEDERAL"),
    (r"\bLey\s+Federal\s+sobre\s+Monumentos\s+y\s+Zonas\s+Arqueológicos,\s+Artísticos\s+e\s+Históricos\b", "LEY FEDERAL SOBRE MONUMENTOS Y ZONAS ARQUEOLÓGICOS, ARTÍSTICOS E HISTÓRICOS", "LEY_FEDERAL"),
    (r"\bLey\s+General\s+de\s+Acceso\s+de\s+las\s+Mujeres\s+a\s+una\s+Vida\s+Libre\s+de\s+Violencia\b", "LEY GENERAL DE ACCESO DE LAS MUJERES A UNA VIDA LIBRE DE VIOLENCIA", "LEY_GENERAL"),
    (r"\bLey\s+General\s+de\s+Archivos\b", "LEY GENERAL DE ARCHIVOS", "LEY_GENERAL"),
    (r"\bLey\s+General\s+de\s+Asentamientos\s+Humanos,\s+Ordenamiento\s+Territorial\s+y\s+Desarrollo\s+Urbano\b", "LEY GENERAL DE ASENTAMIENTOS HUMANOS, ORDENAMIENTO TERRITORIAL Y DESARROLLO URBANO", "LEY_GENERAL"),
    (r"\bLey\s+General\s+de\s+Bibliotecas\b", "LEY GENERAL DE BIBLIOTECAS", "LEY_GENERAL"),
    (r"\bLey\s+General\s+de\s+Bienes\s+Nacionales\b", "LEY GENERAL DE BIENES NACIONALES", "LEY_GENERAL"),
    (r"\bLey\s+General\s+de\s+Cambio\s+Climático\b", "LEY GENERAL DE CAMBIO CLIMÁTICO", "LEY_GENERAL"),
    (r"\bLey\s+General\s+de\s+Comunicación\s+Social\b", "LEY GENERAL DE COMUNICACIÓN SOCIAL", "LEY_GENERAL"),
    (r"\bLey\s+General\s+de\s+Contabilidad\s+Gubernamental\b", "LEY GENERAL DE CONTABILIDAD GUBERNAMENTAL", "LEY_GENERAL"),
    (r"\bLey\s+General\s+de\s+Cultura\s+Física\s+y\s+Deporte\b", "LEY GENERAL DE CULTURA FÍSICA Y DEPORTE", "LEY_GENERAL"),
    (r"\bLey\s+General\s+de\s+Cultura\s+y\s+Derechos\s+Culturales\b", "LEY GENERAL DE CULTURA Y DERECHOS CULTURALES", "LEY_GENERAL"),
    (r"\bLey\s+General\s+de\s+Derechos\s+Lingüísticos\s+de\s+los\s+Pueblos\s+Indígenas\b", "LEY GENERAL DE DERECHOS LINGÜÍSTICOS DE LOS PUEBLOS INDÍGENAS", "LEY_GENERAL"),
    (r"\bLey\s+General\s+de\s+Desarrollo\s+forestal\s+Sustentable\b", "LEY GENERAL DE DESARROLLO FORESTAL SUSTENTABLE", "LEY_GENERAL"),
    (r"\bLey\s+General\s+de\s+Desarrollo\s+Social\b", "LEY GENERAL DE DESARROLLO SOCIAL", "LEY_GENERAL"),
    (r"\bLey\s+General\s+de\s+Educación\b", "LEY GENERAL DE EDUCACIÓN", "LEY_GENERAL"),
    (r"\bLey\s+General\s+de\s+Educación\s+Superior\b", "LEY GENERAL DE EDUCACIÓN SUPERIOR", "LEY_GENERAL"),
    (r"\bLey\s+General\s+de\s+Instituciones\s+y\s+Procedimientos\s+Electorales\b", "LEY GENERAL DE INSTITUCIONES Y PROCEDIMIENTOS ELECTORALES", "LEY_GENERAL"),
    (r"\bLey\s+General\s+De\s+La\s+Alimentación\s+Adecuada\s+y\s+Sostenible\b", "LEY GENERAL DE LA ALIMENTACIÓN ADECUADA Y SOSTENIBLE", "LEY_GENERAL"),
    (r"\bLey\s+General\s+de\s+los\s+Derechos\s+de\s+Niñas,\s+Niños\s+y\s+Adolescentes\b", "LEY GENERAL DE LOS DERECHOS DE NIÑAS, NIÑOS Y ADOLESCENTES", "LEY_GENERAL"),
    (r"\bLey\s+General\s+De\s+Mecanismos\s+Alternativos\s+De\s+Solución\s+De\s+Controversias\b", "LEY GENERAL DE MECANISMOS ALTERNATIVOS DE SOLUCIÓN DE CONTROVERSIAS", "LEY_GENERAL"),
    (r"\bLey\s+General\s+de\s+Mejora\s+Regulatoria\b", "LEY GENERAL DE MEJORA REGULATORIA", "LEY_GENERAL"),
    (r"\bLey\s+General\s+de\s+Movilidad\s+y\s+Seguridad\s+Vial\b", "LEY GENERAL DE MOVILIDAD Y SEGURIDAD VIAL", "LEY_GENERAL"),
    (r"\bLey\s+General\s+de\s+Organizaciones\s+y\s+Actividades\s+Auxiliares\s+del\s+Crédito\b", "LEY GENERAL DE ORGANIZACIONES Y ACTIVIDADES AUXILIARES DEL CRÉDITO", "LEY_GENERAL"),
    (r"\bLey\s+General\s+de\s+Partidos\s+Políticos\b", "LEY GENERAL DE PARTIDOS POLÍTICOS", "LEY_GENERAL"),
    (r"\bLey\s+General\s+de\s+Pesca\s+y\s+Acuacultura\s+Sustentables\b", "LEY GENERAL DE PESCA Y ACUACULTURA SUSTENTABLES", "LEY_GENERAL"),
    (r"\bLey\s+General\s+de\s+Población\b", "LEY GENERAL DE POBLACIÓN", "LEY_GENERAL"),
    (r"\bLey\s+General\s+de\s+Prestación\s+de\s+Servicios\s+para\s+la\s+Atención,\s+Cuidado\s+y\s+Desarrollo\s+Integral\s+Infantil\b", "LEY GENERAL DE PRESTACIÓN DE SERVICIOS PARA LA ATENCIÓN, CUIDADO Y DESARROLLO INTEGRAL INFANTIL", "LEY_GENERAL"),
    (r"\bLey\s+General\s+de\s+Protección\s+Civil\b", "LEY GENERAL DE PROTECCIÓN CIVIL", "LEY_GENERAL"),
    (r"\bLey\s+General\s+de\s+Protección\s+de\s+Datos\s+Personales\s+en\s+Posesión\s+de\s+Sujetos\s+Obligados\b", "LEY GENERAL DE PROTECCIÓN DE DATOS PERSONALES EN POSESIÓN DE SUJETOS OBLIGADOS", "LEY_GENERAL"),
    (r"\bLey\s+General\s+de\s+Responsabilidades\s+Administrativas\b", "LEY GENERAL DE RESPONSABILIDADES ADMINISTRATIVAS", "LEY_GENERAL"),
    (r"\bLey\s+General\s+de\s+Salud\b", "LEY GENERAL DE SALUD", "LEY_GENERAL"),
    (r"\bLey\s+General\s+de\s+Sociedades\s+Cooperativas\b", "LEY GENERAL DE SOCIEDADES COOPERATIVAS", "LEY_GENERAL"),
    (r"\bLey\s+General\s+de\s+Sociedades\s+Mercantiles\b", "LEY GENERAL DE SOCIEDADES MERCANTILES", "LEY_GENERAL"),
    (r"\bLey\s+General\s+de\s+Títulos\s+y\s+Operaciones\s+de\s+Crédito\b", "LEY GENERAL DE TÍTULOS Y OPERACIONES DE CRÉDITO", "LEY_GENERAL"),
    (r"\bLey\s+General\s+de\s+Transparencia\s+y\s+Acceso\s+a\s+la\s+Información\s+Pública\b", "LEY GENERAL DE TRANSPARENCIA Y ACCESO A LA INFORMACIÓN PÚBLICA", "LEY_GENERAL"),
    (r"\bLey\s+General\s+de\s+Turismo\b", "LEY GENERAL DE TURISMO", "LEY_GENERAL"),
    (r"\bLey\s+General\s+de\s+Víctimas\b", "LEY GENERAL DE VÍCTIMAS", "LEY_GENERAL"),
    (r"\bLey\s+General\s+de\s+Vida\s+Silvestre\b", "LEY GENERAL DE VIDA SILVESTRE", "LEY_GENERAL"),
    (r"\bLey\s+General\s+del\s+Equilibrio\s+Ecológico\s+y\s+la\s+Protección\s+al\s+Ambiente\b", "LEY GENERAL DEL EQUILIBRIO ECOLÓGICO Y LA PROTECCIÓN AL AMBIENTE", "LEY_GENERAL"),
    (r"\bLey\s+General\s+del\s+Sistema\s+de\s+Medios\s+de\s+Impugnación\s+en\s+Materia\s+Electoral\b", "LEY GENERAL DEL SISTEMA DE MEDIOS DE IMPUGNACIÓN EN MATERIA ELECTORAL", "LEY_GENERAL"),
    (r"\bLey\s+General\s+del\s+Sistema\s+Nacional\s+Anticorrupción\b", "LEY GENERAL DEL SISTEMA NACIONAL ANTICORRUPCIÓN", "LEY_GENERAL"),
    (r"\bLey\s+General\s+del\s+Sistema\s+Nacional\s+de\s+Seguridad\s+Pública\b", "LEY GENERAL DEL SISTEMA NACIONAL DE SEGURIDAD PÚBLICA", "LEY_GENERAL"),
    (r"\bLey\s+General\s+del\s+Sistema\s+para\s+la\s+Carrera\s+de\s+las\s+Maestras\s+y\s+los\s+Maestros\b", "LEY GENERAL DEL SISTEMA PARA LA CARRERA DE LAS MAESTRAS Y LOS MAESTROS", "LEY_GENERAL"),
    (r"\bLey\s+General\s+en\s+Materia\s+de\s+Delitos\s+Electorales\b", "LEY GENERAL EN MATERIA DE DELITOS ELECTORALES", "LEY_GENERAL"),
    (r"\bLey\s+General\s+en\s+Materia\s+de\s+Desaparición\s+Forzada\s+de\s+Personas,\s+Desaparición\s+Cometida\s+por\s+Particulares\s+y\s+del\s+Sistema\s+Nacional\s+de\s+Búsqueda\s+de\s+Personas\b", "LEY GENERAL EN MATERIA DE DESAPARICIÓN FORZADA DE PERSONAS, DESAPARICIÓN COMETIDA POR PARTICULARES Y DEL SISTEMA NACIONAL DE BÚSQUEDA DE PERSONAS", "LEY_GENERAL"),
    (r"\bLey\s+General\s+en\s+Materia\s+de\s+Humanidades,\s+Ciencias,\s+Tecnologías\s+e\s+Innovación\b", "LEY GENERAL EN MATERIA DE HUMANIDADES, CIENCIAS, TECNOLOGÍAS E INNOVACIÓN", "LEY_GENERAL"),
    (r"\bLey\s+General\s+para\s+el\s+Control\s+del\s+Tabaco\b", "LEY GENERAL PARA EL CONTROL DEL TABACO", "LEY_GENERAL"),
    (r"\bLey\s+General\s+para\s+la\s+Atención\s+y\s+Protección\s+a\s+Personas\s+con\s+la\s+Condición\s+del\s+Espectro\s+Autista\b", "LEY GENERAL PARA LA ATENCIÓN Y PROTECCIÓN A PERSONAS CON LA CONDICIÓN DEL ESPECTRO AUTISTA", "LEY_GENERAL"),
    (r"\bLey\s+General\s+para\s+la\s+Detección\s+Oportuna\s+del\s+Cáncer\s+en\s+la\s+Infancia\s+y\s+la\s+Adolescencia\b", "LEY GENERAL PARA LA DETECCIÓN OPORTUNA DEL CÁNCER EN LA INFANCIA Y LA ADOLESCENCIA", "LEY_GENERAL"),
    (r"\bLey\s+General\s+para\s+la\s+Igualdad\s+entre\s+Mujeres\s+y\s+Hombres\b", "LEY GENERAL PARA LA IGUALDAD ENTRE MUJERES Y HOMBRES", "LEY_GENERAL"),
    (r"\bLey\s+General\s+para\s+la\s+Inclusión\s+de\s+las\s+Personas\s+con\s+Discapacidad\b", "LEY GENERAL PARA LA INCLUSIÓN DE LAS PERSONAS CON DISCAPACIDAD", "LEY_GENERAL"),
    (r"\bLey\s+General\s+para\s+la\s+Prevención\s+Social\s+de\s+la\s+Violencia\s+y\s+la\s+Delincuencia\b", "LEY GENERAL PARA LA PREVENCIÓN SOCIAL DE LA VIOLENCIA Y LA DELINCUENCIA", "LEY_GENERAL"),
    (r"\bLey\s+General\s+para\s+la\s+Prevención\s+y\s+Gestión\s+Integral\s+de\s+los\s+Residuos\b", "LEY GENERAL PARA LA PREVENCIÓN Y GESTIÓN INTEGRAL DE LOS RESIDUOS", "LEY_GENERAL"),
    (r"\bLey\s+General\s+para\s+Prevenir\s+y\s+Sancionar\s+los\s+Delitos\s+en\s+Materia\s+de\s+Secuestro,\s+Reglamentaria\s+de\s+la\s+fracción\s+XXI\s+del\s+Artículo\s+73\s+de\s+la\s+Constitución\s+Política\s+de\s+los\s+Estados\s+Unidos\s+Mexicanos\b", "LEY GENERAL PARA PREVENIR Y SANCIONAR LOS DELITOS EN MATERIA DE SECUESTRO, REGLAMENTARIA DE LA FRACCIÓN XXI DEL ARTÍCULO 73 DE LA CONSTITUCIÓN POLÍTICA DE LOS ESTADOS UNIDOS MEXICANOS", "LEY_GENERAL"),
    (r"\bLey\s+General\s+para\s+Prevenir,\s+Investigar\s+y\s+Sancionar\s+la\s+Tortura\s+y\s+otros\s+Tratos\s+o\s+Penas\s+Crueles,\s+Inhumanos\s+o\s+Degradantes\b", "LEY GENERAL PARA PREVENIR, INVESTIGAR Y SANCIONAR LA TORTURA Y OTROS TRATOS O PENAS CRUELES, INHUMANOS O DEGRADANTES", "LEY_GENERAL"),
    (r"\bLey\s+General\s+para\s+Prevenir,\s+Sancionar\s+y\s+Erradicar\s+los\s+Delitos\s+en\s+Materia\s+de\s+Trata\s+de\s+Personas\s+y\s+para\s+la\s+Protección\s+y\s+Asistencia\s+a\s+las\s+Víctimas\s+de\s+estos\s+Delitos\b", "LEY GENERAL PARA PREVENIR, SANCIONAR Y ERRADICAR LOS DELITOS EN MATERIA DE TRATA DE PERSONAS Y PARA LA PROTECCIÓN Y ASISTENCIA A LAS VÍCTIMAS DE ESTOS DELITOS", "LEY_GENERAL"),
    (r"\bLey\s+Monetaria\s+de\s+los\s+Estados\s+Unidos\s+Mexicanos\b", "LEY MONETARIA DE LOS ESTADOS UNIDOS MEXICANOS", "LEY"),
    (r"\bLey\s+Nacional\s+de\s+Ejecución\s+Penal\b", "LEY NACIONAL DE EJECUCIÓN PENAL", "LEY_NACIONAL"),
    (r"\bLey\s+Nacional\s+de\s+Extinción\s+de\s+Dominio\b", "LEY NACIONAL DE EXTINCIÓN DE DOMINIO", "LEY_NACIONAL"),
    (r"\bLey\s+Nacional\s+de\s+Mecanismos\s+Alternativos\s+de\s+Solución\s+de\s+Controversias\s+en\s+Materia\s+Penal\b", "LEY NACIONAL DE MECANISMOS ALTERNATIVOS DE SOLUCIÓN DE CONTROVERSIAS EN MATERIA PENAL", "LEY_NACIONAL"),
    (r"\bLey\s+Nacional\s+del\s+Registro\s+de\s+Detenciones\b", "LEY NACIONAL DEL REGISTRO DE DETENCIONES", "LEY_NACIONAL"),
    (r"\bLey\s+Nacional\s+del\s+Sistema\s+Integral\s+de\s+Justicia\s+Penal\s+para\s+Adolescentes\b", "LEY NACIONAL DEL SISTEMA INTEGRAL DE JUSTICIA PENAL PARA ADOLESCENTES", "LEY_NACIONAL"),
    (r"\bLey\s+Nacional\s+sobre\s+el\s+Uso\s+de\s+la\s+Fuerza\b", "LEY NACIONAL SOBRE EL USO DE LA FUERZA", "LEY_NACIONAL"),
    (r"\bLey\s+Orgánica\s+de\s+la\s+Administración\s+Pública\s+Federal\b", "LEY ORGÁNICA DE LA ADMINISTRACIÓN PÚBLICA FEDERAL", "LEY_ORGANICA"),
    (r"\bLey\s+Orgánica\s+de\s+la\s+Armada\s+de\s+México\b", "LEY ORGÁNICA DE LA ARMADA DE MÉXICO", "LEY_ORGANICA"),
    (r"\bLey\s+Orgánica\s+de\s+la\s+Procuraduría\s+de\s+la\s+Defensa\s+del\s+Contribuyente\b", "LEY ORGÁNICA DE LA PROCURADURÍA DE LA DEFENSA DEL CONTRIBUYENTE", "LEY_ORGANICA"),
    (r"\bLey\s+Orgánica\s+de\s+la\s+Procuraduría\s+General\s+de\s+Justicia\s+del\s+Distrito\s+Federal\b", "LEY ORGÁNICA DE LA PROCURADURÍA GENERAL DE JUSTICIA DEL DISTRITO FEDERAL", "LEY_ORGANICA"),
    (r"\bLey\s+Orgánica\s+de\s+la\s+Universidad\s+Autónoma\s+Agraria\s+Antonio\s+Narro\b", "LEY ORGÁNICA DE LA UNIVERSIDAD AUTÓNOMA AGRARIA ANTONIO NARRO", "LEY_ORGANICA"),
    (r"\bLey\s+Orgánica\s+de\s+la\s+Universidad\s+Autónoma\s+Metropolitana\b", "LEY ORGÁNICA DE LA UNIVERSIDAD AUTÓNOMA METROPOLITANA", "LEY_ORGANICA"),
    (r"\bLey\s+Orgánica\s+de\s+la\s+Universidad\s+Nacional\s+Autónoma\s+de\s+México\b", "LEY ORGÁNICA DE LA UNIVERSIDAD NACIONAL AUTÓNOMA DE MÉXICO", "LEY_ORGANICA"),
    (r"\bLey\s+Orgánica\s+de\s+los\s+Tribunales\s+Agrarios\b", "LEY ORGÁNICA DE LOS TRIBUNALES AGRARIOS", "LEY_ORGANICA"),
    (r"\bLey\s+Orgánica\s+de\s+Nacional\s+Financiera\b", "LEY ORGÁNICA DE NACIONAL FINANCIERA", "LEY_ORGANICA"),
    (r"\bLey\s+Orgánica\s+de\s+Sociedad\s+Hipotecaria\s+Federal\b", "LEY ORGÁNICA DE SOCIEDAD HIPOTECARIA FEDERAL", "LEY_ORGANICA"),
    (r"\bLey\s+Orgánica\s+del\s+Banco\s+del\s+Bienestar\s+\(antes\s+Ley\s+Orgánica\s+del\s+Banco\s+del\s+Ahorro\s+Nacional\s+y\s+Servicios\s+Financieros\)\b", "LEY ORGÁNICA DEL BANCO DEL BIENESTAR (ANTES LEY ORGÁNICA DEL BANCO DEL AHORRO NACIONAL Y SERVICIOS FINANCIEROS)", "LEY_ORGANICA"),
    (r"\bLey\s+Orgánica\s+del\s+Banco\s+Nacional\s+de\s+Comercio\s+Exterior\b", "LEY ORGÁNICA DEL BANCO NACIONAL DE COMERCIO EXTERIOR", "LEY_ORGANICA"),
    (r"\bLey\s+Orgánica\s+del\s+Banco\s+Nacional\s+de\s+Obras\s+y\s+Servicios\s+Públicos\b", "LEY ORGÁNICA DEL BANCO NACIONAL DE OBRAS Y SERVICIOS PÚBLICOS", "LEY_ORGANICA"),
    (r"\bLey\s+Orgánica\s+del\s+Banco\s+Nacional\s+del\s+Ejército,\s+Fuerza\s+Aérea\s+y\s+Armada\b", "LEY ORGÁNICA DEL BANCO NACIONAL DEL EJÉRCITO, FUERZA AÉREA Y ARMADA", "LEY_ORGANICA"),
    (r"\bLey\s+Orgánica\s+del\s+Centro\s+Federal\s+de\s+Conciliación\s+y\s+Registro\s+Laboral\b", "LEY ORGÁNICA DEL CENTRO FEDERAL DE CONCILIACIÓN Y REGISTRO LABORAL", "LEY_ORGANICA"),
    (r"\bLey\s+Orgánica\s+del\s+Congreso\s+General\s+de\s+los\s+Estados\s+Unidos\s+Mexicanos\b", "LEY ORGÁNICA DEL CONGRESO GENERAL DE LOS ESTADOS UNIDOS MEXICANOS", "LEY_ORGANICA"),
    (r"\bLey\s+Orgánica\s+del\s+Ejército\s+y\s+Fuerza\s+Aérea\s+Mexicanos\b", "LEY ORGÁNICA DEL EJÉRCITO Y FUERZA AÉREA MEXICANOS", "LEY_ORGANICA"),
    (r"\bLey\s+Orgánica\s+del\s+Instituto\s+Nacional\s+de\s+Antropología\s+e\s+Historia\b", "LEY ORGÁNICA DEL INSTITUTO NACIONAL DE ANTROPOLOGÍA E HISTORIA", "LEY_ORGANICA"),
    (r"\bLey\s+Orgánica\s+del\s+Instituto\s+Politécnico\s+Nacional\b", "LEY ORGÁNICA DEL INSTITUTO POLITÉCNICO NACIONAL", "LEY_ORGANICA"),
    (r"\bLey\s+Orgánica\s+del\s+Poder\s+Judicial\s+de\s+la\s+Federación\b", "LEY ORGÁNICA DEL PODER JUDICIAL DE LA FEDERACIÓN", "LEY_ORGANICA"),
    (r"\bLey\s+Orgánica\s+del\s+Seminario\s+de\s+Cultura\s+Mexicana\b", "LEY ORGÁNICA DEL SEMINARIO DE CULTURA MEXICANA", "LEY_ORGANICA"),
    (r"\bLey\s+Orgánica\s+del\s+Tribunal\s+Federal\s+de\s+Justicia\s+Administrativa\b", "LEY ORGÁNICA DEL TRIBUNAL FEDERAL DE JUSTICIA ADMINISTRATIVA", "LEY_ORGANICA"),
    (r"\bLey\s+para\s+Conservar\s+la\s+Neutralidad\s+del\s+País\b", "LEY PARA CONSERVAR LA NEUTRALIDAD DEL PAÍS", "LEY"),
    (r"\bLey\s+para\s+Determinar\s+el\s+Valor\s+de\s+la\s+Unidad\s+de\s+Medida\s+y\s+Actualización\b", "LEY PARA DETERMINAR EL VALOR DE LA UNIDAD DE MEDIDA Y ACTUALIZACIÓN", "LEY"),
    (r"\bLey\s+para\s+el\s+Desarrollo\s+de\s+la\s+Competitividad\s+de\s+la\s+Micro,\s+Pequeña\s+y\s+Mediana\s+Empresa\b", "LEY PARA EL DESARROLLO DE LA COMPETITIVIDAD DE LA MICRO, PEQUEÑA Y MEDIANA EMPRESA", "LEY"),
    (r"\bLey\s+para\s+el\s+Diálogo,\s+la\s+Conciliación\s+y\s+la\s+Paz\s+Digna\s+en\s+Chiapas\b", "LEY PARA EL DIÁLOGO, LA CONCILIACIÓN Y LA PAZ DIGNA EN CHIAPAS", "LEY"),
    (r"\bLey\s+para\s+el\s+uso\s+y\s+protección\s+de\s+la\s+denominación\s+y\s+del\s+emblema\s+de\s+la\s+Cruz\s+Roja\b", "LEY PARA EL USO Y PROTECCIÓN DE LA DENOMINACIÓN Y DEL EMBLEMA DE LA CRUZ ROJA", "LEY"),
    (r"\bLey\s+para\s+Impulsar\s+el\s+Incremento\s+Sostenido\s+de\s+la\s+Productividad\s+y\s+la\s+Competitividad\s+de\s+la\s+Economía\s+Nacional\b", "LEY PARA IMPULSAR EL INCREMENTO SOSTENIDO DE LA PRODUCTIVIDAD Y LA COMPETITIVIDAD DE LA ECONOMÍA NACIONAL", "LEY"),
    (r"\bLey\s+para\s+la\s+Comprobación,\s+Ajuste\s+y\s+Cómputo\s+de\s+Servicios\s+de\s+la\s+Armada\s+de\s+México\b", "LEY PARA LA COMPROBACIÓN, AJUSTE Y CÓMPUTO DE SERVICIOS DE LA ARMADA DE MÉXICO", "LEY"),
    (r"\bLey\s+para\s+la\s+Comprobación,\s+Ajuste\s+y\s+Cómputo\s+de\s+Servicios\s+en\s+el\s+Ejército\s+y\s+Fuerza\s+Aérea\s+Mexicanos\b", "LEY PARA LA COMPROBACIÓN, AJUSTE Y CÓMPUTO DE SERVICIOS EN EL EJÉRCITO Y FUERZA AÉREA MEXICANOS", "LEY"),
    (r"\bLey\s+para\s+la\s+Protección\s+de\s+Personas\s+Defensoras\s+de\s+Derechos\s+Humanos\s+y\s+Periodistas\b", "LEY PARA LA PROTECCIÓN DE PERSONAS DEFENSORAS DE DERECHOS HUMANOS Y PERIODISTAS", "LEY"),
    (r"\bLey\s+para\s+la\s+Transparencia\s+y\s+Ordenamiento\s+de\s+los\s+Servicios\s+Financieros\b", "LEY PARA LA TRANSPARENCIA Y ORDENAMIENTO DE LOS SERVICIOS FINANCIEROS", "LEY"),
    (r"\bLey\s+para\s+la\s+Transparencia,\s+Prevención\s+y\s+Combate\s+de\s+Prácticas\s+Indebidas\s+en\s+Materia\s+de\s+Contratación\s+de\s+Publicidad\.\b", "LEY PARA LA TRANSPARENCIA, PREVENCIÓN Y COMBATE DE PRÁCTICAS INDEBIDAS EN MATERIA DE CONTRATACIÓN DE PUBLICIDAD.", "LEY"),
    (r"\bLey\s+para\s+Regular\s+las\s+Actividades\s+de\s+las\s+Sociedades\s+Cooperativas\s+de\s+Ahorro\s+y\s+Préstamo\b", "LEY PARA REGULAR LAS ACTIVIDADES DE LAS SOCIEDADES COOPERATIVAS DE AHORRO Y PRÉSTAMO", "LEY"),
    (r"\bLey\s+para\s+Regular\s+las\s+Agrupaciones\s+Financieras\b", "LEY PARA REGULAR LAS AGRUPACIONES FINANCIERAS", "LEY"),
    (r"\bLey\s+para\s+Regular\s+las\s+Instituciones\s+de\s+Tecnología\s+Financiera\b", "LEY PARA REGULAR LAS INSTITUCIONES DE TECNOLOGÍA FINANCIERA", "LEY"),
    (r"\bLey\s+para\s+regular\s+las\s+Sociedades\s+de\s+Información\s+Crediticia\b", "LEY PARA REGULAR LAS SOCIEDADES DE INFORMACIÓN CREDITICIA", "LEY"),
    (r"\bLey\s+que\s+aprueba\s+la\s+Adhesión\s+de\s+México\s+al\s+Convenio\s+Constitutivo\s+del\s+Banco\s+de\s+Desarrollo\s+del\s+Caribe\s+y\s+su\s+Ejecución\b", "LEY QUE APRUEBA LA ADHESIÓN DE MÉXICO AL CONVENIO CONSTITUTIVO DEL BANCO DE DESARROLLO DEL CARIBE Y SU EJECUCIÓN", "LEY"),
    (r"\bLey\s+que\s+crea\s+el\s+Fondo\s+de\s+Garantía\s+y\s+Fomento\s+para\s+la\s+Agricultura,\s+Ganadería\s+y\s+Avicultura\b", "LEY QUE CREA EL FONDO DE GARANTÍA Y FOMENTO PARA LA AGRICULTURA, GANADERÍA Y AVICULTURA", "LEY"),
    (r"\bLey\s+que\s+crea\s+el\s+Instituto\s+Nacional\s+de\s+Bellas\s+Artes\s+y\s+Literatura\b", "LEY QUE CREA EL INSTITUTO NACIONAL DE BELLAS ARTES Y LITERATURA", "LEY"),
    (r"\bLey\s+que\s+crea\s+la\s+Agencia\s+Espacial\s+Mexicana\b", "LEY QUE CREA LA AGENCIA ESPACIAL MEXICANA", "LEY"),
    (r"\bLey\s+que\s+crea\s+la\s+Universidad\s+Autónoma\s+Chapingo\b", "LEY QUE CREA LA UNIVERSIDAD AUTÓNOMA CHAPINGO", "LEY"),
    (r"\bLey\s+que\s+crea\s+la\s+Universidad\s+del\s+Ejército\s+y\s+Fuerza\s+Aérea\b", "LEY QUE CREA LA UNIVERSIDAD DEL EJÉRCITO Y FUERZA AÉREA", "LEY"),
    (r"\bLey\s+que\s+declara\s+Reservas\s+Mineras\s+Nacionales\s+los\s+Yacimientos\s+de\s+Uranio,\s+Torio\s+y\s+las\s+demás\s+Substancias\s+de\s+las\s+cuales\s+se\s+obtengan\s+Isótopos\s+Hendibles\s+que\s+puedan\s+producir\s+Energía\s+Nuclear\b", "LEY QUE DECLARA RESERVAS MINERAS NACIONALES LOS YACIMIENTOS DE URANIO, TORIO Y LAS DEMÁS SUBSTANCIAS DE LAS CUALES SE OBTENGAN ISÓTOPOS HENDIBLES QUE PUEDAN PRODUCIR ENERGÍA NUCLEAR", "LEY"),
    (r"\bLey\s+que\s+establece\s+Bases\s+para\s+la\s+Ejecución\s+en\s+México,\s+por\s+el\s+Poder\s+Ejecutivo\s+Federal,\s+del\s+Convenio\s+Constitutivo\s+de\s+la\s+Asociación\s+Internacional\s+de\s+Fomento\b", "LEY QUE ESTABLECE BASES PARA LA EJECUCIÓN EN MÉXICO, POR EL PODER EJECUTIVO FEDERAL, DEL CONVENIO CONSTITUTIVO DE LA ASOCIACIÓN INTERNACIONAL DE FOMENTO", "LEY"),
    (r"\bLey\s+que\s+establece\s+Bases\s+para\s+la\s+Ejecución\s+en\s+México,\s+por\s+el\s+Poder\s+Ejecutivo\s+Federal,\s+del\s+Convenio\s+Constitutivo\s+del\s+Banco\s+Interamericano\s+de\s+Desarrollo\b", "LEY QUE ESTABLECE BASES PARA LA EJECUCIÓN EN MÉXICO, POR EL PODER EJECUTIVO FEDERAL, DEL CONVENIO CONSTITUTIVO DEL BANCO INTERAMERICANO DE DESARROLLO", "LEY"),
    (r"\bLey\s+Reglamentaria\s+de\s+la\s+Fracción\s+V\s+del\s+Artículo\s+76\s+de\s+la\s+Constitución\s+General\s+de\s+la\s+República\b", "LEY REGLAMENTARIA DE LA FRACCIÓN V DEL ARTÍCULO 76 DE LA CONSTITUCIÓN GENERAL DE LA REPÚBLICA", "CONSTITUCION"),
    (r"\bLey\s+Reglamentaria\s+de\s+la\s+Fracción\s+VI\s+del\s+Artículo\s+76\s+de\s+la\s+Constitución\s+Política\s+de\s+los\s+Estados\s+Unidos\s+Mexicanos\b", "LEY REGLAMENTARIA DE LA FRACCIÓN VI DEL ARTÍCULO 76 DE LA CONSTITUCIÓN POLÍTICA DE LOS ESTADOS UNIDOS MEXICANOS", "CONSTITUCION"),
    (r"\bLey\s+Reglamentaria\s+de\s+la\s+Fracción\s+XIII\s+Bis\s+del\s+Apartado\s+B,\s+del\s+Artículo\s+123\s+de\s+la\s+Constitución\s+Política\s+de\s+los\s+Estados\s+Unidos\s+Mexicanos\b", "LEY REGLAMENTARIA DE LA FRACCIÓN XIII BIS DEL APARTADO B, DEL ARTÍCULO 123 DE LA CONSTITUCIÓN POLÍTICA DE LOS ESTADOS UNIDOS MEXICANOS", "CONSTITUCION"),
    (r"\bLey\s+Reglamentaria\s+de\s+la\s+Fracción\s+XVIII\s+del\s+Artículo\s+73\s+Constitucional,\s+en\s+lo\s+que\s+se\s+refiere\s+a\s+la\s+facultad\s+del\s+Congreso\s+para\s+dictar\s+reglas\s+para\s+determinar\s+el\s+valor\s+relativo\s+de\s+la\s+Moneda\s+Extranjera\b", "LEY REGLAMENTARIA DE LA FRACCIÓN XVIII DEL ARTÍCULO 73 CONSTITUCIONAL, EN LO QUE SE REFIERE A LA FACULTAD DEL CONGRESO PARA DICTAR REGLAS PARA DETERMINAR EL VALOR RELATIVO DE LA MONEDA EXTRANJERA", "LEY"),
    (r"\bLey\s+Reglamentaria\s+de\s+las\s+Fracciones\s+I\s+y\s+II\s+del\s+Artículo\s+105\s+de\s+la\s+Constitución\s+Política\s+de\s+los\s+Estados\s+Unidos\s+Mexicanos\b", "LEY REGLAMENTARIA DE LAS FRACCIONES I Y II DEL ARTÍCULO 105 DE LA CONSTITUCIÓN POLÍTICA DE LOS ESTADOS UNIDOS MEXICANOS", "CONSTITUCION"),
    (r"\bLey\s+Reglamentaria\s+del\s+Artículo\s+27\s+Constitucional\s+en\s+Materia\s+Nuclear\b", "LEY REGLAMENTARIA DEL ARTÍCULO 27 CONSTITUCIONAL EN MATERIA NUCLEAR", "LEY"),
    (r"\bLey\s+Reglamentaria\s+del\s+Artículo\s+3o\.\s+de\s+la\s+Constitución\s+Política\s+de\s+los\s+Estados\s+Unidos\s+Mexicanos,\s+en\s+materia\s+de\s+Mejora\s+Continua\s+de\s+la\s+Educación\b", "LEY REGLAMENTARIA DEL ARTÍCULO 3O. DE LA CONSTITUCIÓN POLÍTICA DE LOS ESTADOS UNIDOS MEXICANOS, EN MATERIA DE MEJORA CONTINUA DE LA EDUCACIÓN", "CONSTITUCION"),
    (r"\bLey\s+Reglamentaria\s+del\s+Artículo\s+6o\.\s+párrafo\s+primero,\s+de\s+la\s+Constitución\s+Política\s+de\s+los\s+Estados\s+Unidos\s+Mexicanos\s+en\s+materia\s+del\s+Derecho\s+de\s+Réplica\b", "LEY REGLAMENTARIA DEL ARTÍCULO 6O. PÁRRAFO PRIMERO, DE LA CONSTITUCIÓN POLÍTICA DE LOS ESTADOS UNIDOS MEXICANOS EN MATERIA DEL DERECHO DE RÉPLICA", "CONSTITUCION"),
    (r"\bLey\s+Reglamentaria\s+del\s+Servicio\s+Ferroviario\b", "LEY REGLAMENTARIA DEL SERVICIO FERROVIARIO", "LEY"),
    (r"\bLey\s+sobre\s+Cámaras\s+Agrícolas,\s+que\s+en\s+lo\s+sucesivo\s+se\s+denominarán\s+Asociaciones\s+Agrícolas\b", "LEY SOBRE CÁMARAS AGRÍCOLAS, QUE EN LO SUCESIVO SE DENOMINARÁN ASOCIACIONES AGRÍCOLAS", "LEY"),
    (r"\bLey\s+sobre\s+el\s+Contrato\s+de\s+Seguro\b", "LEY SOBRE EL CONTRATO DE SEGURO", "LEY"),
    (r"\bLey\s+sobre\s+el\s+Escudo,\s+la\s+Bandera\s+y\s+el\s+Himno\s+Nacionales\b", "LEY SOBRE EL ESCUDO, LA BANDERA Y EL HIMNO NACIONALES", "LEY"),
    (r"\bLey\s+sobre\s+Elaboración\s+y\s+Venta\s+de\s+Café\s+Tostado\b", "LEY SOBRE ELABORACIÓN Y VENTA DE CAFÉ TOSTADO", "LEY"),
    (r"\bLey\s+sobre\s+la\s+Aprobación\s+de\s+Tratados\s+Internacionales\s+en\s+Materia\s+Económica\b", "LEY SOBRE LA APROBACIÓN DE TRATADOS INTERNACIONALES EN MATERIA ECONÓMICA", "LEY"),
    (r"\bLey\s+sobre\s+la\s+Celebración\s+de\s+Tratados\b", "LEY SOBRE LA CELEBRACIÓN DE TRATADOS", "LEY"),
    (r"\bLey\s+sobre\s+Refugiados,\s+Protección\s+Complementaria\s+y\s+Asilo\s+Político\b", "LEY SOBRE REFUGIADOS, PROTECCIÓN COMPLEMENTARIA Y ASILO POLÍTICO", "LEY"),
    (r"\bOrdenanza\s+General\s+de\s+la\s+Armada\b", "ORDENANZA GENERAL DE LA ARMADA", "OTRO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+Aduanera\b", "REGLAMENTO DE LA LEY ADUANERA", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+Agraria\s+en\s+Materia\s+de\s+Certificación\s+de\s+Derechos\s+Ejidales\s+y\s+Titulación\s+de\s+Solares\b", "REGLAMENTO DE LA LEY AGRARIA EN MATERIA DE CERTIFICACIÓN DE DERECHOS EJIDALES Y TITULACIÓN DE SOLARES", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+Agraria\s+en\s+Materia\s+de\s+Ordenamiento\s+de\s+la\s+Propiedad\s+Rural\b", "REGLAMENTO DE LA LEY AGRARIA EN MATERIA DE ORDENAMIENTO DE LA PROPIEDAD RURAL", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+Agraria\s+para\s+Fomentar\s+la\s+Organización\s+y\s+Desarrollo\s+de\s+la\s+Mujer\s+Campesina\b", "REGLAMENTO DE LA LEY AGRARIA PARA FOMENTAR LA ORGANIZACIÓN Y DESARROLLO DE LA MUJER CAMPESINA", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+Adquisiciones,\s+Arrendamientos\s+y\s+Servicios\s+del\s+Sector\s+Público\b", "REGLAMENTO DE LA LEY DE ADQUISICIONES, ARRENDAMIENTOS Y SERVICIOS DEL SECTOR PÚBLICO", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+Aeropuertos\b", "REGLAMENTO DE LA LEY DE AEROPUERTOS", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+Aguas\s+Nacionales\b", "REGLAMENTO DE LA LEY DE AGUAS NACIONALES", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+Ascensos\s+de\s+la\s+Armada\s+de\s+México\b", "REGLAMENTO DE LA LEY DE ASCENSOS DE LA ARMADA DE MÉXICO", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+Ascensos\s+y\s+Recompensas\s+del\s+Ejército\s+y\s+Fuerza\s+Aérea\s+Mexicanos\b", "REGLAMENTO DE LA LEY DE ASCENSOS Y RECOMPENSAS DEL EJÉRCITO Y FUERZA AÉREA MEXICANOS", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+Asociaciones\s+Público\s+Privadas\b", "REGLAMENTO DE LA LEY DE ASOCIACIONES PÚBLICO PRIVADAS", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+Asociaciones\s+Religiosas\s+y\s+Culto\s+Público\b", "REGLAMENTO DE LA LEY DE ASOCIACIONES RELIGIOSAS Y CULTO PÚBLICO", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+Aviación\s+Civil\b", "REGLAMENTO DE LA LEY DE AVIACIÓN CIVIL", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+Ayuda\s+Alimentaria\s+para\s+los\s+Trabajadores\b", "REGLAMENTO DE LA LEY DE AYUDA ALIMENTARIA PARA LOS TRABAJADORES", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+Bioseguridad\s+de\s+Organismos\s+Genéticamente\s+Modificados\b", "REGLAMENTO DE LA LEY DE BIOSEGURIDAD DE ORGANISMOS GENÉTICAMENTE MODIFICADOS", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+Cámaras\s+Empresariales\s+y\s+sus\s+Confederaciones\b", "REGLAMENTO DE LA LEY DE CÁMARAS EMPRESARIALES Y SUS CONFEDERACIONES", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+Comercio\s+Exterior\b", "REGLAMENTO DE LA LEY DE COMERCIO EXTERIOR", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+Desarrollo\s+Rural\s+Sustentable\s+en\s+Materia\s+de\s+Organismos,\s+Instancias\s+de\s+Representación,\s+Sistemas\s+y\s+Servicios\s+Especializados\b", "REGLAMENTO DE LA LEY DE DESARROLLO RURAL SUSTENTABLE EN MATERIA DE ORGANISMOS, INSTANCIAS DE REPRESENTACIÓN, SISTEMAS Y SERVICIOS ESPECIALIZADOS", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+Educación\s+Militar\s+del\s+Ejército\s+y\s+Fuerza\s+Aérea\s+Mexicanos\b", "REGLAMENTO DE LA LEY DE EDUCACIÓN MILITAR DEL EJÉRCITO Y FUERZA AÉREA MEXICANOS", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+Educación\s+Naval\b", "REGLAMENTO DE LA LEY DE EDUCACIÓN NAVAL", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+Energía\s+Geotérmica\b", "REGLAMENTO DE LA LEY DE ENERGÍA GEOTÉRMICA", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+Energía\s+para\s+el\s+Campo\b", "REGLAMENTO DE LA LEY DE ENERGÍA PARA EL CAMPO", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+Firma\s+Electrónica\s+Avanzada\b", "REGLAMENTO DE LA LEY DE FIRMA ELECTRÓNICA AVANZADA", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+Fomento\s+para\s+la\s+Lectura\s+y\s+el\s+Libro\b", "REGLAMENTO DE LA LEY DE FOMENTO PARA LA LECTURA Y EL LIBRO", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+Hidrocarburos\b", "REGLAMENTO DE LA LEY DE HIDROCARBUROS", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+Información\s+Estadística\s+y\s+Geográfica\b", "REGLAMENTO DE LA LEY DE INFORMACIÓN ESTADÍSTICA Y GEOGRÁFICA", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+Ingresos\s+sobre\s+Hidrocarburos\b", "REGLAMENTO DE LA LEY DE INGRESOS SOBRE HIDROCARBUROS", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+Inversión\s+Extranjera\s+y\s+del\s+Registro\s+Nacional\s+de\s+Inversiones\s+Extranjeras\b", "REGLAMENTO DE LA LEY DE INVERSIÓN EXTRANJERA Y DEL REGISTRO NACIONAL DE INVERSIONES EXTRANJERAS", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+la\s+Comisión\s+Federal\s+de\s+Electricidad\b", "REGLAMENTO DE LA LEY DE LA COMISIÓN FEDERAL DE ELECTRICIDAD", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+la\s+Guardia\s+Nacional\b", "REGLAMENTO DE LA LEY DE LA GUARDIA NACIONAL", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+la\s+Industria\s+Eléctrica\b", "REGLAMENTO DE LA LEY DE LA INDUSTRIA ELÉCTRICA", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+la\s+Policía\s+Federal\b", "REGLAMENTO DE LA LEY DE LA POLICÍA FEDERAL", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+la\s+Propiedad\s+Industrial\b", "REGLAMENTO DE LA LEY DE LA PROPIEDAD INDUSTRIAL", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+los\s+Sistemas\s+de\s+Ahorro\s+para\s+el\s+Retiro\b", "REGLAMENTO DE LA LEY DE LOS SISTEMAS DE AHORRO PARA EL RETIRO", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+Migración\b", "REGLAMENTO DE LA LEY DE MIGRACIÓN", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+Nacionalidad\b", "REGLAMENTO DE LA LEY DE NACIONALIDAD", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+Navegación\s+y\s+Comercio\s+Marítimos\b", "REGLAMENTO DE LA LEY DE NAVEGACIÓN Y COMERCIO MARÍTIMOS", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+Obras\s+Públicas\s+y\s+Servicios\s+Relacionados\s+con\s+las\s+Mismas\b", "REGLAMENTO DE LA LEY DE OBRAS PÚBLICAS Y SERVICIOS RELACIONADOS CON LAS MISMAS", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+Organizaciones\s+Ganaderas\b", "REGLAMENTO DE LA LEY DE ORGANIZACIONES GANADERAS", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+Pesca\b", "REGLAMENTO DE LA LEY DE PESCA", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+Petróleos\s+Mexicanos\b", "REGLAMENTO DE LA LEY DE PETRÓLEOS MEXICANOS", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+Productos\s+Orgánicos\b", "REGLAMENTO DE LA LEY DE PRODUCTOS ORGÁNICOS", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+Promoción\s+y\s+Desarrollo\s+de\s+los\s+Bioenergéticos\b", "REGLAMENTO DE LA LEY DE PROMOCIÓN Y DESARROLLO DE LOS BIOENERGÉTICOS", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+Puertos\b", "REGLAMENTO DE LA LEY DE PUERTOS", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+Tesorería\s+de\s+la\s+Federación\b", "REGLAMENTO DE LA LEY DE TESORERÍA DE LA FEDERACIÓN", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+de\s+Transición\s+Energética\b", "REGLAMENTO DE LA LEY DE TRANSICIÓN ENERGÉTICA", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+del\s+Impuesto\s+al\s+Valor\s+Agregado\b", "REGLAMENTO DE LA LEY DEL IMPUESTO AL VALOR AGREGADO", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+del\s+Impuesto\s+Especial\s+sobre\s+Producción\s+y\s+Servicios\b", "REGLAMENTO DE LA LEY DEL IMPUESTO ESPECIAL SOBRE PRODUCCIÓN Y SERVICIOS", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+del\s+Impuesto\s+sobre\s+la\s+Renta\b", "REGLAMENTO DE LA LEY DEL IMPUESTO SOBRE LA RENTA", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+del\s+Instituto\s+de\s+Seguridad\s+Social\s+para\s+las\s+Fuerzas\s+Armadas\s+Mexicanas\b", "REGLAMENTO DE LA LEY DEL INSTITUTO DE SEGURIDAD SOCIAL PARA LAS FUERZAS ARMADAS MEXICANAS", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+del\s+Instituto\s+del\s+Fondo\s+Nacional\s+de\s+la\s+Vivienda\s+para\s+los\s+Trabajadores\s+en\s+Materia\s+de\s+Transparencia\s+y\s+Acceso\s+a\s+la\s+Información\b", "REGLAMENTO DE LA LEY DEL INSTITUTO DEL FONDO NACIONAL DE LA VIVIENDA PARA LOS TRABAJADORES EN MATERIA DE TRANSPARENCIA Y ACCESO A LA INFORMACIÓN", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+del\s+Instituto\s+del\s+Fondo\s+Nacional\s+para\s+el\s+Consumo\s+de\s+los\s+Trabajadores\b", "REGLAMENTO DE LA LEY DEL INSTITUTO DEL FONDO NACIONAL PARA EL CONSUMO DE LOS TRABAJADORES", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+del\s+Registro\s+Público\s+Vehicular\b", "REGLAMENTO DE LA LEY DEL REGISTRO PÚBLICO VEHICULAR", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+del\s+Seguro\s+Social\s+en\s+Materia\s+de\s+Afiliación,\s+Clasificación\s+de\s+Empresas,\s+Recaudación\s+y\s+Fiscalización\b", "REGLAMENTO DE LA LEY DEL SEGURO SOCIAL EN MATERIA DE AFILIACIÓN, CLASIFICACIÓN DE EMPRESAS, RECAUDACIÓN Y FISCALIZACIÓN", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+del\s+Seguro\s+Social\s+para\s+la\s+Constitución,\s+Inversión\s+y\s+Uso\s+para\s+la\s+Operación\s+de\s+las\s+Reservas\s+Financieras\s+y\s+Actuariales\s+y\s+la\s+Reserva\s+General\s+Financiera\s+y\s+Actuarial,\s+así\s+como\s+para\s+la\s+Determinación\s+de\s+los\s+Costos\s+Financieros\s+que\s+Deberán\s+Reintegrarse\s+a\s+la\s+Reserva\s+de\s+Operación\s+para\s+Contingencias\s+y\s+Financiamiento\b", "REGLAMENTO DE LA LEY DEL SEGURO SOCIAL PARA LA CONSTITUCIÓN, INVERSIÓN Y USO PARA LA OPERACIÓN DE LAS RESERVAS FINANCIERAS Y ACTUARIALES Y LA RESERVA GENERAL FINANCIERA Y ACTUARIAL, ASÍ COMO PARA LA DETERMINACIÓN DE LOS COSTOS FINANCIEROS QUE DEBERÁN REINTEGRARSE A LA RESERVA DE OPERACIÓN PARA CONTINGENCIAS Y FINANCIAMIENTO", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+del\s+Seguro\s+Social,\s+en\s+Materia\s+de\s+Administración\s+y\s+Enajenación\s+de\s+Bienes\s+Adjudicados\s+con\s+Motivo\s+de\s+la\s+Aplicación\s+del\s+Procedimiento\s+Administrativo\s+de\s+Ejecución\b", "REGLAMENTO DE LA LEY DEL SEGURO SOCIAL, EN MATERIA DE ADMINISTRACIÓN Y ENAJENACIÓN DE BIENES ADJUDICADOS CON MOTIVO DE LA APLICACIÓN DEL PROCEDIMIENTO ADMINISTRATIVO DE EJECUCIÓN", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+del\s+Servicio\s+Exterior\s+Mexicano\b", "REGLAMENTO DE LA LEY DEL SERVICIO EXTERIOR MEXICANO", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+del\s+Servicio\s+Militar\b", "REGLAMENTO DE LA LEY DEL SERVICIO MILITAR", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+del\s+Servicio\s+Profesional\s+de\s+Carrera\s+en\s+la\s+Administración\s+Pública\s+Federal\b", "REGLAMENTO DE LA LEY DEL SERVICIO PROFESIONAL DE CARRERA EN LA ADMINISTRACIÓN PÚBLICA FEDERAL", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+del\s+Servicio\s+Público\s+de\s+Energía\s+Eléctrica,\s+en\s+Materia\s+de\s+Aportaciones\b", "REGLAMENTO DE LA LEY DEL SERVICIO PÚBLICO DE ENERGÍA ELÉCTRICA, EN MATERIA DE APORTACIONES", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+Federal\s+de\s+Archivos\b", "REGLAMENTO DE LA LEY FEDERAL DE ARCHIVOS", "LEY_FEDERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+Federal\s+de\s+Armas\s+de\s+Fuego\s+y\s+Explosivos\b", "REGLAMENTO DE LA LEY FEDERAL DE ARMAS DE FUEGO Y EXPLOSIVOS", "LEY_FEDERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+Federal\s+de\s+Cinematografía\b", "REGLAMENTO DE LA LEY FEDERAL DE CINEMATOGRAFÍA", "LEY_FEDERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+Federal\s+de\s+Competencia\s+Económica\b", "REGLAMENTO DE LA LEY FEDERAL DE COMPETENCIA ECONÓMICA", "LEY_FEDERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+Federal\s+de\s+Correduría\s+Pública\b", "REGLAMENTO DE LA LEY FEDERAL DE CORREDURÍA PÚBLICA", "LEY_FEDERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+Federal\s+de\s+Fomento\s+a\s+las\s+Actividades\s+Realizadas\s+por\s+Organizaciones\s+de\s+la\s+Sociedad\s+Civil\b", "REGLAMENTO DE LA LEY FEDERAL DE FOMENTO A LAS ACTIVIDADES REALIZADAS POR ORGANIZACIONES DE LA SOCIEDAD CIVIL", "LEY_FEDERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+Federal\s+de\s+Juegos\s+y\s+Sorteos\b", "REGLAMENTO DE LA LEY FEDERAL DE JUEGOS Y SORTEOS", "LEY_FEDERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+Federal\s+de\s+las\s+Entidades\s+Paraestatales\b", "REGLAMENTO DE LA LEY FEDERAL DE LAS ENTIDADES PARAESTATALES", "LEY_FEDERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+Federal\s+de\s+Presupuesto\s+y\s+Responsabilidad\s+Hacendaria\b", "REGLAMENTO DE LA LEY FEDERAL DE PRESUPUESTO Y RESPONSABILIDAD HACENDARIA", "LEY_FEDERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+Federal\s+de\s+Producción,\s+Certificación\s+y\s+Comercio\s+de\s+Semillas\b", "REGLAMENTO DE LA LEY FEDERAL DE PRODUCCIÓN, CERTIFICACIÓN Y COMERCIO DE SEMILLAS", "LEY_FEDERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+Federal\s+de\s+Protección\s+al\s+Consumidor\b", "REGLAMENTO DE LA LEY FEDERAL DE PROTECCIÓN AL CONSUMIDOR", "LEY_FEDERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+Federal\s+de\s+Protección\s+de\s+Datos\s+Personales\s+en\s+Posesión\s+de\s+los\s+Particulares\b", "REGLAMENTO DE LA LEY FEDERAL DE PROTECCIÓN DE DATOS PERSONALES EN POSESIÓN DE LOS PARTICULARES", "LEY_FEDERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+Federal\s+de\s+Radio\s+y\s+Televisión,\s+en\s+Materia\s+de\s+Concesiones,\s+Permisos\s+y\s+Contenido\s+de\s+las\s+Transmisiones\s+de\s+Radio\s+y\s+Televisión\b", "REGLAMENTO DE LA LEY FEDERAL DE RADIO Y TELEVISIÓN, EN MATERIA DE CONCESIONES, PERMISOS Y CONTENIDO DE LAS TRANSMISIONES DE RADIO Y TELEVISIÓN", "LEY_FEDERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+Federal\s+de\s+Sanidad\s+Animal\b", "REGLAMENTO DE LA LEY FEDERAL DE SANIDAD ANIMAL", "LEY_FEDERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+Federal\s+de\s+Sanidad\s+Vegetal\b", "REGLAMENTO DE LA LEY FEDERAL DE SANIDAD VEGETAL", "LEY_FEDERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+Federal\s+de\s+Seguridad\s+Privada\b", "REGLAMENTO DE LA LEY FEDERAL DE SEGURIDAD PRIVADA", "LEY_FEDERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+Federal\s+de\s+Telecomunicaciones\s+y\s+Radiodifusión\s+en\s+Materia\s+de\s+Capacidad\s+Satelital\s+como\s+reserva\s+del\s+Estado\b", "REGLAMENTO DE LA LEY FEDERAL DE TELECOMUNICACIONES Y RADIODIFUSIÓN EN MATERIA DE CAPACIDAD SATELITAL COMO RESERVA DEL ESTADO", "LEY_FEDERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+Federal\s+de\s+Transparencia\s+y\s+Acceso\s+a\s+la\s+Información\s+Pública\s+Gubernamental\b", "REGLAMENTO DE LA LEY FEDERAL DE TRANSPARENCIA Y ACCESO A LA INFORMACIÓN PÚBLICA GUBERNAMENTAL", "LEY_FEDERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+Federal\s+de\s+Variedades\s+Vegetales\b", "REGLAMENTO DE LA LEY FEDERAL DE VARIEDADES VEGETALES", "LEY_FEDERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+Federal\s+de\s+Zonas\s+Económicas\s+Especiales\b", "REGLAMENTO DE LA LEY FEDERAL DE ZONAS ECONÓMICAS ESPECIALES", "LEY_FEDERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+Federal\s+del\s+Derecho\s+de\s+Autor\b", "REGLAMENTO DE LA LEY FEDERAL DEL DERECHO DE AUTOR", "LEY_FEDERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+Federal\s+para\s+el\s+Control\s+de\s+Precursores\s+Químicos,\s+Productos\s+Químicos\s+Esenciales\s+y\s+Máquinas\s+para\s+Elaborar\s+Cápsulas,\s+Tabletas\s+y/o\s+Comprimidos\b", "REGLAMENTO DE LA LEY FEDERAL PARA EL CONTROL DE PRECURSORES QUÍMICOS, PRODUCTOS QUÍMICOS ESENCIALES Y MÁQUINAS PARA ELABORAR CÁPSULAS, TABLETAS Y/O COMPRIMIDOS", "LEY_FEDERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+Federal\s+para\s+la\s+Administración\s+y\s+Enajenación\s+de\s+Bienes\s+del\s+Sector\s+Público\b", "REGLAMENTO DE LA LEY FEDERAL PARA LA ADMINISTRACIÓN Y ENAJENACIÓN DE BIENES DEL SECTOR PÚBLICO", "LEY_FEDERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+Federal\s+para\s+la\s+Prevención\s+e\s+Identificación\s+de\s+Operaciones\s+con\s+Recursos\s+de\s+Procedencia\s+Ilícita\b", "REGLAMENTO DE LA LEY FEDERAL PARA LA PREVENCIÓN E IDENTIFICACIÓN DE OPERACIONES CON RECURSOS DE PROCEDENCIA ILÍCITA", "LEY_FEDERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+Federal\s+sobre\s+Metrología\s+y\s+Normalización\b", "REGLAMENTO DE LA LEY FEDERAL SOBRE METROLOGÍA Y NORMALIZACIÓN", "LEY_FEDERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+Federal\s+sobre\s+Monumentos\s+y\s+Zonas\s+Arqueológicas,\s+Artísticos\s+e\s+Históricos\b", "REGLAMENTO DE LA LEY FEDERAL SOBRE MONUMENTOS Y ZONAS ARQUEOLÓGICAS, ARTÍSTICOS E HISTÓRICOS", "LEY_FEDERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+General\s+de\s+Acceso\s+de\s+las\s+Mujeres\s+a\s+una\s+Vida\s+Libre\s+de\s+Violencia\b", "REGLAMENTO DE LA LEY GENERAL DE ACCESO DE LAS MUJERES A UNA VIDA LIBRE DE VIOLENCIA", "LEY_GENERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+General\s+de\s+Cambio\s+Climático\s+en\s+Materia\s+del\s+Registro\s+Nacional\s+de\s+Emisiones\b", "REGLAMENTO DE LA LEY GENERAL DE CAMBIO CLIMÁTICO EN MATERIA DEL REGISTRO NACIONAL DE EMISIONES", "LEY_GENERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+General\s+de\s+Cultura\s+Física\s+y\s+Deporte\b", "REGLAMENTO DE LA LEY GENERAL DE CULTURA FÍSICA Y DEPORTE", "LEY_GENERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+General\s+de\s+Cultura\s+y\s+Derechos\s+Culturales\b", "REGLAMENTO DE LA LEY GENERAL DE CULTURA Y DERECHOS CULTURALES", "LEY_GENERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+General\s+de\s+Desarrollo\s+Forestal\s+Sustentable\b", "REGLAMENTO DE LA LEY GENERAL DE DESARROLLO FORESTAL SUSTENTABLE", "LEY_GENERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+General\s+de\s+Desarrollo\s+Social\b", "REGLAMENTO DE LA LEY GENERAL DE DESARROLLO SOCIAL", "LEY_GENERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+General\s+de\s+la\s+Infraestructura\s+Física\s+Educativa\b", "REGLAMENTO DE LA LEY GENERAL DE LA INFRAESTRUCTURA FÍSICA EDUCATIVA", "LEY_GENERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+General\s+de\s+los\s+Derechos\s+de\s+Niñas,\s+Niños\s+y\s+Adolescentes\b", "REGLAMENTO DE LA LEY GENERAL DE LOS DERECHOS DE NIÑAS, NIÑOS Y ADOLESCENTES", "LEY_GENERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+General\s+de\s+Población\b", "REGLAMENTO DE LA LEY GENERAL DE POBLACIÓN", "LEY_GENERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+General\s+de\s+Prestación\s+de\s+Servicios\s+para\s+la\s+Atención,\s+Cuidado\s+y\s+Desarrollo\s+Integral\s+Infantil\b", "REGLAMENTO DE LA LEY GENERAL DE PRESTACIÓN DE SERVICIOS PARA LA ATENCIÓN, CUIDADO Y DESARROLLO INTEGRAL INFANTIL", "LEY_GENERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+General\s+de\s+Protección\s+Civil\b", "REGLAMENTO DE LA LEY GENERAL DE PROTECCIÓN CIVIL", "LEY_GENERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+General\s+de\s+Salud\s+en\s+Materia\s+de\s+Control\s+Sanitario\s+de\s+Actividades,\s+Establecimientos,\s+Productos\s+y\s+Servicios\b", "REGLAMENTO DE LA LEY GENERAL DE SALUD EN MATERIA DE CONTROL SANITARIO DE ACTIVIDADES, ESTABLECIMIENTOS, PRODUCTOS Y SERVICIOS", "LEY_GENERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+General\s+de\s+Salud\s+en\s+Materia\s+de\s+Control\s+Sanitario\s+de\s+la\s+Disposición\s+de\s+Órganos,\s+Tejidos\s+y\s+Cadáveres\s+de\s+Seres\s+Humanos\b", "REGLAMENTO DE LA LEY GENERAL DE SALUD EN MATERIA DE CONTROL SANITARIO DE LA DISPOSICIÓN DE ÓRGANOS, TEJIDOS Y CADÁVERES DE SERES HUMANOS", "LEY_GENERAL"),
    (r"\bREGLAMENTO\s+de\s+la\s+Ley\s+General\s+de\s+Salud\s+en\s+Materia\s+de\s+Control\s+Sanitario\s+para\s+la\s+Producción,\s+Investigación\s+y\s+Uso\s+Medicinal\s+de\s+la\s+Cannabis\s+y\s+sus\s+Derivados\s+Farmacológicos\.\b", "REGLAMENTO DE LA LEY GENERAL DE SALUD EN MATERIA DE CONTROL SANITARIO PARA LA PRODUCCIÓN, INVESTIGACIÓN Y USO MEDICINAL DE LA CANNABIS Y SUS DERIVADOS FARMACOLÓGICOS.", "LEY_GENERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+General\s+de\s+Salud\s+en\s+Materia\s+de\s+Investigación\s+para\s+la\s+Salud\b", "REGLAMENTO DE LA LEY GENERAL DE SALUD EN MATERIA DE INVESTIGACIÓN PARA LA SALUD", "LEY_GENERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+General\s+de\s+Salud\s+en\s+Materia\s+de\s+Prestación\s+de\s+Servicios\s+de\s+Atención\s+Médica\b", "REGLAMENTO DE LA LEY GENERAL DE SALUD EN MATERIA DE PRESTACIÓN DE SERVICIOS DE ATENCIÓN MÉDICA", "LEY_GENERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+General\s+de\s+Salud\s+en\s+Materia\s+de\s+Protección\s+Social\s+en\s+Salud\b", "REGLAMENTO DE LA LEY GENERAL DE SALUD EN MATERIA DE PROTECCIÓN SOCIAL EN SALUD", "LEY_GENERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+General\s+de\s+Salud\s+en\s+Materia\s+de\s+Publicidad\b", "REGLAMENTO DE LA LEY GENERAL DE SALUD EN MATERIA DE PUBLICIDAD", "LEY_GENERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+General\s+de\s+Salud\s+en\s+Materia\s+de\s+Sanidad\s+Internacional\b", "REGLAMENTO DE LA LEY GENERAL DE SALUD EN MATERIA DE SANIDAD INTERNACIONAL", "LEY_GENERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+General\s+de\s+Salud\s+en\s+Materia\s+de\s+Trasplantes\b", "REGLAMENTO DE LA LEY GENERAL DE SALUD EN MATERIA DE TRASPLANTES", "LEY_GENERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+General\s+de\s+Turismo\b", "REGLAMENTO DE LA LEY GENERAL DE TURISMO", "LEY_GENERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+General\s+de\s+Víctimas\b", "REGLAMENTO DE LA LEY GENERAL DE VÍCTIMAS", "LEY_GENERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+General\s+de\s+Vida\s+Silvestre\b", "REGLAMENTO DE LA LEY GENERAL DE VIDA SILVESTRE", "LEY_GENERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+General\s+del\s+Equilibrio\s+Ecológico\s+y\s+la\s+Protección\s+al\s+Ambiente\s+en\s+Materia\s+de\s+Áreas\s+Naturales\s+Protegidas\b", "REGLAMENTO DE LA LEY GENERAL DEL EQUILIBRIO ECOLÓGICO Y LA PROTECCIÓN AL AMBIENTE EN MATERIA DE ÁREAS NATURALES PROTEGIDAS", "LEY_GENERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+General\s+del\s+Equilibrio\s+Ecológico\s+y\s+la\s+Protección\s+al\s+Ambiente\s+en\s+Materia\s+de\s+Autorregulación\s+y\s+Auditorías\s+Ambientales\b", "REGLAMENTO DE LA LEY GENERAL DEL EQUILIBRIO ECOLÓGICO Y LA PROTECCIÓN AL AMBIENTE EN MATERIA DE AUTORREGULACIÓN Y AUDITORÍAS AMBIENTALES", "LEY_GENERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+General\s+del\s+Equilibrio\s+Ecológico\s+y\s+la\s+Protección\s+al\s+Ambiente\s+en\s+Materia\s+de\s+Evaluación\s+del\s+Impacto\s+Ambiental\b", "REGLAMENTO DE LA LEY GENERAL DEL EQUILIBRIO ECOLÓGICO Y LA PROTECCIÓN AL AMBIENTE EN MATERIA DE EVALUACIÓN DEL IMPACTO AMBIENTAL", "LEY_GENERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+General\s+del\s+Equilibrio\s+Ecológico\s+y\s+la\s+Protección\s+al\s+Ambiente\s+en\s+Materia\s+de\s+Ordenamiento\s+Ecológico\b", "REGLAMENTO DE LA LEY GENERAL DEL EQUILIBRIO ECOLÓGICO Y LA PROTECCIÓN AL AMBIENTE EN MATERIA DE ORDENAMIENTO ECOLÓGICO", "LEY_GENERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+General\s+del\s+Equilibrio\s+Ecológico\s+y\s+la\s+Protección\s+al\s+Ambiente\s+en\s+Materia\s+de\s+Prevención\s+y\s+Control\s+de\s+la\s+Contaminación\s+de\s+la\s+Atmósfera\b", "REGLAMENTO DE LA LEY GENERAL DEL EQUILIBRIO ECOLÓGICO Y LA PROTECCIÓN AL AMBIENTE EN MATERIA DE PREVENCIÓN Y CONTROL DE LA CONTAMINACIÓN DE LA ATMÓSFERA", "LEY_GENERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+General\s+del\s+Equilibrio\s+Ecológico\s+y\s+la\s+Protección\s+al\s+Ambiente\s+en\s+Materia\s+de\s+Registro\s+de\s+Emisiones\s+y\s+Transferencia\s+de\s+Contaminantes\b", "REGLAMENTO DE LA LEY GENERAL DEL EQUILIBRIO ECOLÓGICO Y LA PROTECCIÓN AL AMBIENTE EN MATERIA DE REGISTRO DE EMISIONES Y TRANSFERENCIA DE CONTAMINANTES", "LEY_GENERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+General\s+para\s+el\s+Control\s+del\s+Tabaco\b", "REGLAMENTO DE LA LEY GENERAL PARA EL CONTROL DEL TABACO", "LEY_GENERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+General\s+para\s+la\s+Atención\s+y\s+Protección\s+a\s+Personas\s+con\s+la\s+Condición\s+del\s+Espectro\s+Autista\b", "REGLAMENTO DE LA LEY GENERAL PARA LA ATENCIÓN Y PROTECCIÓN A PERSONAS CON LA CONDICIÓN DEL ESPECTRO AUTISTA", "LEY_GENERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+General\s+para\s+la\s+Inclusión\s+de\s+las\s+Personas\s+con\s+Discapacidad\b", "REGLAMENTO DE LA LEY GENERAL PARA LA INCLUSIÓN DE LAS PERSONAS CON DISCAPACIDAD", "LEY_GENERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+General\s+para\s+la\s+Prevención\s+Social\s+de\s+la\s+Violencia\s+y\s+la\s+Delincuencia\b", "REGLAMENTO DE LA LEY GENERAL PARA LA PREVENCIÓN SOCIAL DE LA VIOLENCIA Y LA DELINCUENCIA", "LEY_GENERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+General\s+para\s+la\s+Prevención\s+y\s+Gestión\s+Integral\s+de\s+los\s+Residuos\b", "REGLAMENTO DE LA LEY GENERAL PARA LA PREVENCIÓN Y GESTIÓN INTEGRAL DE LOS RESIDUOS", "LEY_GENERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+General\s+para\s+Prevenir,\s+Sancionar\s+y\s+Erradicar\s+los\s+Delitos\s+en\s+Materia\s+de\s+Trata\s+de\s+Personas\s+y\s+para\s+la\s+Protección\s+y\s+Asistencia\s+a\s+las\s+Víctimas\s+de\s+estos\s+Delitos\b", "REGLAMENTO DE LA LEY GENERAL PARA PREVENIR, SANCIONAR Y ERRADICAR LOS DELITOS EN MATERIA DE TRATA DE PERSONAS Y PARA LA PROTECCIÓN Y ASISTENCIA A LAS VÍCTIMAS DE ESTOS DELITOS", "LEY_GENERAL"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+Minera\b", "REGLAMENTO DE LA LEY MINERA", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+Orgánica\s+de\s+la\s+Procuraduría\s+General\s+de\s+la\s+República\b", "REGLAMENTO DE LA LEY ORGÁNICA DE LA PROCURADURÍA GENERAL DE LA REPÚBLICA", "LEY_ORGANICA"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+Orgánica\s+del\s+Instituto\s+Nacional\s+de\s+Antropología\s+e\s+Historia\b", "REGLAMENTO DE LA LEY ORGÁNICA DEL INSTITUTO NACIONAL DE ANTROPOLOGÍA E HISTORIA", "LEY_ORGANICA"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+para\s+el\s+Desarrollo\s+de\s+la\s+Competitividad\s+de\s+la\s+Micro,\s+Pequeña\s+y\s+Mediana\s+Empresa\b", "REGLAMENTO DE LA LEY PARA EL DESARROLLO DE LA COMPETITIVIDAD DE LA MICRO, PEQUEÑA Y MEDIANA EMPRESA", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+para\s+el\s+Uso\s+y\s+Protección\s+de\s+la\s+Denominación\s+y\s+del\s+Emblema\s+de\s+la\s+Cruz\s+Roja\b", "REGLAMENTO DE LA LEY PARA EL USO Y PROTECCIÓN DE LA DENOMINACIÓN Y DEL EMBLEMA DE LA CRUZ ROJA", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+para\s+la\s+Protección\s+de\s+Personas\s+Defensoras\s+de\s+Derechos\s+Humanos\s+y\s+Periodistas\b", "REGLAMENTO DE LA LEY PARA LA PROTECCIÓN DE PERSONAS DEFENSORAS DE DERECHOS HUMANOS Y PERIODISTAS", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+que\s+Crea\s+el\s+Fondo\s+de\s+Garantía\s+y\s+Fomento\s+para\s+la\s+Agricultura,\s+Ganadería\s+y\s+Avicultura\b", "REGLAMENTO DE LA LEY QUE CREA EL FONDO DE GARANTÍA Y FOMENTO PARA LA AGRICULTURA, GANADERÍA Y AVICULTURA", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+que\s+Declara\s+Reservas\s+Mineras\s+Nacionales\s+los\s+Yacimientos\s+de\s+Uranio,\s+Torio\s+y\s+las\s+demás\s+Substancias\s+de\s+las\s+cuales\s+se\s+obtengan\s+Isótopos\s+Hendibles\s+que\s+puedan\s+producir\s+Energía\s+Nuclear\b", "REGLAMENTO DE LA LEY QUE DECLARA RESERVAS MINERAS NACIONALES LOS YACIMIENTOS DE URANIO, TORIO Y LAS DEMÁS SUBSTANCIAS DE LAS CUALES SE OBTENGAN ISÓTOPOS HENDIBLES QUE PUEDAN PRODUCIR ENERGÍA NUCLEAR", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+la\s+Ley\s+sobre\s+Refugiados\s+y\s+Protección\s+Complementaria\b", "REGLAMENTO DE LA LEY SOBRE REFUGIADOS Y PROTECCIÓN COMPLEMENTARIA", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+las\s+actividades\s+a\s+que\s+se\s+refiere\s+el\s+Título\s+Tercero\s+de\s+la\s+Ley\s+de\s+Hidrocarburos\b", "REGLAMENTO DE LAS ACTIVIDADES A QUE SE REFIERE EL TÍTULO TERCERO DE LA LEY DE HIDROCARBUROS", "REGLAMENTO"),
    (r"\bReglamento\s+de\s+los\s+Artículos\s+121\s+y\s+122\s+de\s+la\s+Ley\s+Federal\s+del\s+Trabajo\b", "REGLAMENTO DE LOS ARTÍCULOS 121 Y 122 DE LA LEY FEDERAL DEL TRABAJO", "LEY_FEDERAL"),
    (r"\bReglamento\s+del\s+Artículo\s+122\s+de\s+la\s+Ley\s+Federal\s+de\s+Protección\s+al\s+Consumidor\b", "REGLAMENTO DEL ARTÍCULO 122 DE LA LEY FEDERAL DE PROTECCIÓN AL CONSUMIDOR", "LEY_FEDERAL"),
    (r"\bReglamento\s+del\s+Artículo\s+95\s+de\s+la\s+Ley\s+Federal\s+de\s+Instituciones\s+de\s+Fianzas,\s+para\s+el\s+cobro\s+de\s+fianzas\s+otorgadas\s+a\s+favor\s+de\s+la\s+Federación,\s+del\s+Distrito\s+Federal,\s+de\s+los\s+Estados\s+y\s+de\s+los\s+Municipios,\s+distintas\s+de\s+las\s+que\s+garantizan\s+obligaciones\s+fiscales\s+federales\s+a\s+cargo\s+de\s+terceros\b", "REGLAMENTO DEL ARTÍCULO 95 DE LA LEY FEDERAL DE INSTITUCIONES DE FIANZAS, PARA EL COBRO DE FIANZAS OTORGADAS A FAVOR DE LA FEDERACIÓN, DEL DISTRITO FEDERAL, DE LOS ESTADOS Y DE LOS MUNICIPIOS, DISTINTAS DE LAS QUE GARANTIZAN OBLIGACIONES FISCALES FEDERALES A CARGO DE TERCEROS", "LEY_FEDERAL"),
    (r"\bReglamento\s+del\s+Código\s+de\s+Comercio\s+en\s+Materia\s+de\s+Prestadores\s+de\s+Servicios\s+de\s+Certificación\b", "REGLAMENTO DEL CÓDIGO DE COMERCIO EN MATERIA DE PRESTADORES DE SERVICIOS DE CERTIFICACIÓN", "CODIGO"),
    (r"\bReglamento\s+del\s+Código\s+Fiscal\s+de\s+la\s+Federación\b", "REGLAMENTO DEL CÓDIGO FISCAL DE LA FEDERACIÓN", "CODIGO"),
]

LAW_CATEGORIES = {
    "CODIGO": "Codigo",
    "CODIGO_FEDERAL": "Codigo Federal",
    "CONSTITUCION": "Constitucion",
    "LEY": "Ley",
    "LEY_FEDERAL": "Ley Federal",
    "LEY_GENERAL": "Ley General",
    "LEY_NACIONAL": "Ley Nacional",
    "LEY_ORGANICA": "Ley Organica",
    "OTRO": "Otro",
    "REGLAMENTO": "Reglamento",
}
